// Build entry — bundles the runtime to a single inlinable IIFE string and emits
// the committed generated module that @leadbay/core imports. Mirrors the
// promptforge emit pattern (writeIfDifferent + AUTO-GENERATED header; the
// generated file lives in src/, not dist/, so it is committed source).
//
// Run via `tsx src/build.ts` (the package's `build` script). @leadbay/core's
// `prebuild` runs this before its tsc so the generated string is fresh.

import { build as esbuild } from "esbuild";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { VERSION } from "./runtime.js";

const RUNTIME_ENTRY = fileURLToPath(new URL("./runtime.ts", import.meta.url));
const USAGE_GUIDE = fileURLToPath(new URL("./usage-guide.md", import.meta.url));
const OUT = fileURLToPath(
  new URL("../../core/src/artifact-runtime.generated.ts", import.meta.url),
);
// The finished boards and the country outlines they draw. A second module so
// the ~900 KB of outline geometry does not sit in the runtime/guide one.
const TEMPLATES_DIR = fileURLToPath(new URL("./templates/", import.meta.url));
const BASEMAPS_DIR = fileURLToPath(new URL("./basemaps/", import.meta.url));
const TEMPLATES_OUT = fileURLToPath(
  new URL("../../core/src/artifact-templates.generated.ts", import.meta.url),
);

const HEADER = `// AUTO-GENERATED by @leadbay/components — do not edit directly.
// Regenerate via: pnpm --filter @leadbay/components build
// Source-of-truth: packages/components/src/{runtime.ts, usage-guide.md}

`;

async function bundleRuntime(): Promise<string> {
  const result = await esbuild({
    entryPoints: [RUNTIME_ENTRY],
    bundle: true,
    minify: true,
    format: "iife",
    // No globalName: the runtime self-attaches `window.LeadbayArtifacts` from
    // inside its module body (see runtime.ts), which is robust across script VMs
    // that don't expose esbuild's top-level `var` (jsdom, wrapped <script>).
    target: ["es2020"],
    legalComments: "none",
    write: false,
  });
  return result.outputFiles[0].text.trim();
}

function writeIfDifferent(path: string, content: string): boolean {
  mkdirSync(dirname(path), { recursive: true });
  if (existsSync(path) && readFileSync(path, "utf8") === content) return false;
  writeFileSync(path, content, "utf8");
  return true;
}

async function main(): Promise<void> {
  const runtime = await bundleRuntime();
  // Normalize CRLF: the guide is JSON.stringify'd into a string literal, so a
  // CRLF checkout would bake `\r\n` escapes into the committed module — escapes
  // git cannot normalize, unlike real CR bytes (product#4044).
  const usageGuide = readFileSync(USAGE_GUIDE, "utf8").replace(/\r\n/g, "\n").trimEnd();

  // JSON.stringify gives a safely-escaped TS string literal — no backtick or
  // `${` hazards from the minified runtime or the markdown.
  const module =
    HEADER +
    `export const ARTIFACT_KIT_VERSION = ${JSON.stringify(VERSION)};\n\n` +
    `/** Minified, self-contained IIFE. Inline once per artifact; it self-attaches\n` +
    ` *  window.LeadbayArtifacts (lb.field / lb.action / lb.resource / lb.list / …).\n` +
    ` *  Zero dependencies. */\n` +
    `export const ARTIFACT_RUNTIME: string = ${JSON.stringify(runtime)};\n\n` +
    `/** Markdown assembly recipe the agent reads to build an artifact. */\n` +
    `export const ARTIFACT_USAGE_GUIDE: string = ${JSON.stringify(usageGuide)};\n`;

  const templatesModule = buildTemplatesModule(runtime);
  const rel = "packages/core/src/artifact-runtime.generated.ts";
  const templatesRel = "packages/core/src/artifact-templates.generated.ts";

  // Drift guard: `build --check` verifies the committed generated module matches
  // a fresh build, and FAILS otherwise — so editing runtime.ts/usage-guide.md
  // without re-running the build can't silently ship a stale runtime/guide.
  if (process.argv.includes("--check")) {
    const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : null;
    if (current !== module) {
      console.error(
        `[components] DRIFT: ${rel} is stale. Run \`pnpm --filter @leadbay/components build\` and commit the result.`,
      );
      process.exit(1);
    }
    const currentTemplates = existsSync(TEMPLATES_OUT) ? readFileSync(TEMPLATES_OUT, "utf8") : null;
    if (currentTemplates !== templatesModule) {
      console.error(
        `[components] DRIFT: ${templatesRel} is stale. Run \`pnpm --filter @leadbay/components build\` and commit the result.`,
      );
      process.exit(1);
    }
    console.log(`[components] ${rel}: up to date`);
    return;
  }

  const changed = writeIfDifferent(OUT, module);
  console.log(
    `[components] ${rel}: ${changed ? "wrote" : "unchanged"} ` +
      `(runtime ${runtime.length}B, guide ${usageGuide.length}B)`,
  );
  const changedTemplates = writeIfDifferent(TEMPLATES_OUT, templatesModule);
  console.log(`[components] ${templatesRel}: ${changedTemplates ? "wrote" : "unchanged"}`);
}

// A template is a finished board: its page (markup + styles), the CURRENT
// runtime inlined once, and its script. An agent publishes the result as it
// is, so every user who asks for the board gets the same page. `</script` is
// escaped so neither the runtime nor the page script can close its own tag.
interface TemplateDef { dir: string; title: string; icon: string; description: string; tools: string[] }
function buildTemplatesModule(runtime: string): string {
  const esc = (js: string) => js.replace(/<\/script/gi, "<\\/script");
  const read = (path: string) => readFileSync(path, "utf8").replace(/\r\n/g, "\n").trimEnd();
  const defs = JSON.parse(read(TEMPLATES_DIR + "templates.json")) as Record<string, TemplateDef>;
  const templates: Record<string, unknown> = {};
  for (const [name, def] of Object.entries(defs)) {
    const page = read(TEMPLATES_DIR + def.dir + "/page.html");
    const app = read(TEMPLATES_DIR + def.dir + "/app.js");
    const html = `${page}\n<script>${esc(runtime)}</script>\n<script>${esc(app)}</script>\n`;
    templates[name] = { title: def.title, icon: def.icon, description: def.description, tools: def.tools, html };
  }
  // Re-stringified so the committed module carries no whitespace or CRLF.
  // Stored as ready-made JSON STRINGS: the server pretty-prints every result
  // (JSON.stringify(result, null, 2)), which puts each of ~100k coordinates on
  // its own indented line — 2.5 MB for France as an object, 560 KB as a string.
  const basemaps = {
    fr: JSON.stringify(JSON.parse(read(BASEMAPS_DIR + "fr.json"))),
    us: JSON.stringify(JSON.parse(read(BASEMAPS_DIR + "us.json"))),
  };
  return (
    HEADER.replace("{runtime.ts, usage-guide.md}", "{templates/, basemaps/} + runtime.ts") +
    `/** Finished boards, keyed by name. \`html\` is published as it is. */\n` +
    `export const ARTIFACT_TEMPLATES: Record<string, { title: string; icon: string; description: string; tools: string[]; html: string }> = ${JSON.stringify(templates)};\n\n` +
    `/** Country outlines by workspace region, as GeoJSON serialized to a string. */\n` +
    `export const ARTIFACT_BASEMAPS: Record<string, string> = ${JSON.stringify(basemaps)};\n`
  );
}

main().catch((err) => {
  console.error("[components] build failed:", err);
  process.exit(1);
});
