// Build entry — bundles the runtime to a single inlinable IIFE string and emits
// the committed generated module that @leadbay/core imports. Mirrors the
// promptforge emit pattern (writeIfDifferent + AUTO-GENERATED header; the
// generated file lives in src/, not dist/, so it is committed source).
//
// Run via `tsx src/build.ts` (the package's `build` script). @leadbay/core's
// `prebuild` runs this before its tsc so the generated string is fresh.

import { build as esbuild } from "esbuild";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { VERSION } from "./runtime.js";

const RUNTIME_ENTRY = fileURLToPath(new URL("./runtime.ts", import.meta.url));
const USAGE_GUIDE = fileURLToPath(new URL("./usage-guide.md", import.meta.url));
const OUT = fileURLToPath(
  new URL("../../core/src/artifact-runtime.generated.ts", import.meta.url),
);

const HEADER = `// AUTO-GENERATED by @leadbay/components — do not edit directly.
// Regenerate via: pnpm --filter @leadbay/components build
// Source-of-truth: packages/components/src/{runtime.ts, usage-guide.md}

`;

async function bundleRuntime(): Promise<string> {
  const result = await esbuild({
    entryPoints: [RUNTIME_ENTRY],
    bundle: true,
    minify: true,
    format: "iife",
    // No globalName: the runtime self-attaches `window.LeadbayArtifacts` from
    // inside its module body (see runtime.ts), which is robust across script VMs
    // that don't expose esbuild's top-level `var` (jsdom, wrapped <script>).
    target: ["es2020"],
    legalComments: "none",
    write: false,
  });
  return result.outputFiles[0].text.trim();
}

function writeIfDifferent(path: string, content: string): boolean {
  mkdirSync(dirname(path), { recursive: true });
  if (existsSync(path) && readFileSync(path, "utf8") === content) return false;
  writeFileSync(path, content, "utf8");
  return true;
}

async function main(): Promise<void> {
  const runtime = await bundleRuntime();
  const usageGuide = readFileSync(USAGE_GUIDE, "utf8").trimEnd();

  // JSON.stringify gives a safely-escaped TS string literal — no backtick or
  // `${` hazards from the minified runtime or the markdown.
  const module =
    HEADER +
    `export const ARTIFACT_KIT_VERSION = ${JSON.stringify(VERSION)};\n\n` +
    `/** Minified, self-contained IIFE. Inline once per artifact; it self-attaches\n` +
    ` *  window.LeadbayArtifacts (lb.field / lb.action / lb.resource / lb.list / …).\n` +
    ` *  Zero dependencies. */\n` +
    `export const ARTIFACT_RUNTIME: string = ${JSON.stringify(runtime)};\n\n` +
    `/** Markdown assembly recipe the agent reads to build an artifact. */\n` +
    `export const ARTIFACT_USAGE_GUIDE: string = ${JSON.stringify(usageGuide)};\n`;

  const rel = "packages/core/src/artifact-runtime.generated.ts";

  // Drift guard: `build --check` verifies the committed generated module matches
  // a fresh build, and FAILS otherwise — so editing runtime.ts/usage-guide.md
  // without re-running the build can't silently ship a stale runtime/guide.
  if (process.argv.includes("--check")) {
    const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : null;
    if (current !== module) {
      console.error(
        `[components] DRIFT: ${rel} is stale. Run \`pnpm --filter @leadbay/components build\` and commit the result.`,
      );
      process.exit(1);
    }
    console.log(`[components] ${rel}: up to date`);
    return;
  }

  const changed = writeIfDifferent(OUT, module);
  console.log(
    `[components] ${rel}: ${changed ? "wrote" : "unchanged"} ` +
      `(runtime ${runtime.length}B, guide ${usageGuide.length}B)`,
  );
}

main().catch((err) => {
  console.error("[components] build failed:", err);
  process.exit(1);
});
