// AUTO-GENERATED by @leadbay/promptforge — do not edit directly.
// Regenerate via: pnpm prompts:build
// Source-of-truth: packages/promptforge/{prompts,tool-descriptions}/*.md.tmpl

// Routing test set per tool: sentences that SHOULD call it (positive) and
// confusable ones that should NOT (negative). Not shipped in descriptions.
export interface RoutingExamples {
  positive: string[];
  negative: string[];
}

export const ROUTING_EXAMPLES: Record<string, RoutingExamples> = {
  leadbay_account_history: {
    positive: ["What's the full history on this account — why did it resurface?", "Summarize everything we've logged on that lead and whether it's worth another visit."],
    negative: ["Tell me the current AI take on this lead.", "Which accounts should I follow up with this week?"],
  },
  leadbay_account_status: {
    positive: ["What's my account status?", "How much quota do I have left this week?", "Which version of the Leadbay connector is this?"],
    negative: ["Show me today's leads.", "What should I follow up on?"],
  },
  leadbay_add_contact: {
    positive: ["Acme has no suggested contacts — add Jane Doe, VP Eng, here's her LinkedIn.", "Add this person I found on LinkedIn to that company.", "Create a contact for John Smith, CFO, on this lead."],
    negative: ["Import these 40 domains from my CRM and qualify them.", "Get me the email for the contact already on this company.", "Remove that contact, it's the wrong person."],
  },
  leadbay_add_leads_to_campaign: {
    positive: ["Add the three new Tulsa leads to my 'OK Sweep' campaign.", "Attach these qualified leads to campaign id 1f12...?", "Put the top 5 of today's batch into my Q2 Push."],
    negative: ["Create a new campaign with these 9 leads.", "What campaigns do I have?", "Show progression on my Limoges Tour."],
  },
  leadbay_adjust_audience: {
    positive: ["Add fintech to my Joinery lens.", "Narrow my audience to manufacturing companies, 50–500 people.", "Restrict my rep's lens to Indre-et-Loire."],
    negative: ["Create a lens called Joinery for fintech.", "Show me my lenses.", "Focus on hospitals that run their own IT.", "Show me companies anywhere in the US."],
  },
  leadbay_campaign_call_sheet: {
    positive: ["Show me my Limoges Tour campaign as a call sheet.", "I'm about to do a calling session — render the Q2 Push campaign.", "Give me phones + LinkedIn for everyone in my OK Sweep campaign."],
    negative: ["Quick pulse on how my campaigns are doing.", "Save these 9 leads as a new campaign.", "Tell me about Acme Corp."],
  },
  leadbay_campaign_progression: {
    positive: ["Walk me through the Limoges Tour campaign — who have I touched?", "Show progression on campaign 1f12...?", "What's stuck in my Q2 Push?"],
    negative: ["Show me all my campaigns.", "Create a new campaign.", "Log that I emailed Acme."],
  },
  leadbay_create_campaign: {
    positive: ["Save these 9 leads as a campaign called 'Limoges Tour – May 24'.", "Create a campaign for the qualified leads I just picked.", "Make a campaign for my SF visit and add those three accounts.", "Prepare 3 email campaigns to re-engage my prospects."],
    negative: ["What campaigns do I have?", "Add three more leads to my 'Q2 Push' campaign.", "I just emailed Acme — log it."],
  },
  leadbay_dislike_lead: {
    positive: ["Thumbs down — wrong industry.", "Dislike this one, never show me leads like this again.", "Not a fit at all, remove it."],
    negative: ["Skip this for now, ask me again next month.", "I'll look at this one later.", "I like this lead — save it."],
  },
  leadbay_enrich_contacts: {
    positive: ["Get me Jane Doe's email at Acme.", "Enrich the managing director at Cromology, not the president.", "Reveal the phone number for this contact."],
    negative: ["Enrich the CEOs across my top 10 leads.", "Pin Jane Doe as the main contact on Acme.", "Draft an outreach email for Acme."],
  },
  leadbay_extend_lens: {
    positive: ["Give me more leads on this lens — I want a bigger batch.", "Extend the lens, I've burned through what I had.", "Add 30 more leads like the ones in this batch."],
    negative: ["Show me today's leads.", "Narrow the audience to fintech only.", "Which leads should I follow up with this week?"],
  },
  leadbay_find_new_leads: {
    positive: ["Find me 10 gyms around Dallas that would buy our flooring, with a contact.", "Get me 20 new US SaaS companies, 50-2000 employees, with the VP People's email.", "We're launching in Lyon — find 15 hotels that fit our ICP."],
    negative: ["Show me today's leads.", "Which leads should I follow up with this week?", "Qualify these 40 websites from my spreadsheet."],
  },
  leadbay_followups_map: {
    positive: ["I'm flying to New York Thursday — who should I meet in person?", "Who can I visit while I'm in Chicago next week?"],
    negative: ["What should I follow up on this week?", "Tell me about Acme Corp."],
  },
  leadbay_get_artifact_runtime: {
    positive: ["Build me an interactive call sheet for these leads.", "Make an artifact with buttons to log call outcomes per lead.", "I want a clickable lead-triage board I can work down."],
    negative: ["Show me today's leads.", "Which leads should I follow up with this week?", "Log that I emailed Acme's CTO."],
  },
  leadbay_get_lead_custom_fields: {
    positive: ["What custom field values are stored on this lead?", "Show me the CRM custom fields for that company."],
    negative: ["What custom fields are defined on my account?", "Give me the full research breakdown on Acme Corp."],
  },
  leadbay_get_qualification_questions: {
    positive: ["What qualification questions does Leadbay use to score my leads?", "Show me my org's qualification questions.", "Why do I keep getting these companies? What are my settings?"],
    negative: ["How did Acme Corp answer the qualification questions?", "Add a question about install crews."],
  },
  leadbay_getting_started: {
    positive: ["Walk me through Leadbay.", "I'm new here — how do I use this?", "Can you show me how this works?"],
    negative: ["Show me today's leads.", "Explain the difference between discovery and follow-up.", "Which of my lenses is active right now?"],
  },
  leadbay_lead_job_status: {
    positive: ["Any leads yet from that search you started?", "Wait for the qualification job to finish and show me everything."],
    negative: ["Is the email enrichment finished?", "Is my CSV import done?"],
  },
  leadbay_like_lead: {
    positive: ["I like this lead — show me more like it.", "Thumbs up on Acme Corp, save it.", "This one's a perfect fit, keep them in the rotation."],
    negative: ["Skip this for now, I'll look at it next week.", "Not relevant — wrong industry.", "Just show me the top leads today."],
  },
  leadbay_list_campaigns: {
    positive: ["What campaigns am I running?", "Show me my active campaigns and how they're doing.", "Quick pulse on my campaigns."],
    negative: ["Create a 'Q2 Push' campaign.", "How are leads progressing in my Limoges Tour?", "Today's fresh leads.", "Prepare 3 email campaigns to re-engage my prospects."],
  },
  leadbay_list_lens_seed_candidates: {
    positive: ["(agent-internal) user asked for more leads — fetch seeds before calling extend_lens", "(agent-internal) the lens came back empty and the user agreed to widen it — read the seeds extend_lens will draw from"],
    negative: ["Show me today's leads.", "Restrict the audience to fintech only.", "Which leads should I follow up with this week?"],
  },
  leadbay_manage_lenses: {
    positive: ["Show me my lenses.", "What criteria is my Manufacturing lens using? I want to add or remove some.", "Rename my Auto lens to Automotive and add a description.", "Delete my old Auto lens."],
    negative: ["Narrow the audience to fintech only.", "I want more leads on this lens.", "Show me today's leads."],
  },
  leadbay_new_lens: {
    positive: ["Create a lens called Joinery for the fintech sector.", "Make me a new audience for healthcare companies, 30–300 people.", "Create a lens for net-new accounts in Indre-et-Loire."],
    negative: ["Add fintech to my Joinery lens.", "Show me my lenses.", "I want more leads on this lens.", "Show me companies anywhere in the US."],
  },
  leadbay_pin_contact: {
    positive: ["Pin Jane Doe as the main contact on this company.", "Mark this person as the priority contact.", "Favourite that contact so it shows first."],
    negative: ["Add a contact to this company.", "Remove that contact, wrong person.", "Stop showing me this lead."],
  },
  leadbay_prepare_outreach: {
    positive: ["Draft an email to Sarah at Acme.", "I'm about to call Acme's CTO — prep me."],
    negative: ["I just sent that email — log it.", "Research the Acme lead before I commit."],
  },
  leadbay_pull_followups: {
    positive: ["What should I follow up on this week?", "What's overdue in my pipeline?", "Show me leads I should reach out to today."],
    negative: ["Show me today's new leads.", "Draft an email to Sarah at Acme."],
  },
  leadbay_pull_leads: {
    positive: ["Show me today's leads.", "Pull my best new prospects."],
    negative: ["Find me 10 gyms around Dallas that would buy our flooring.", "Which leads should I follow up with this week?", "I'm flying to Berlin Thursday — who should I meet?", "I'm in San Francisco next Tuesday — who's worth meeting?", "Show me leads I should reach out to today.", "Who should I get back to today?", "Leads I should contact today."],
  },
  leadbay_qualify_leads: {
    positive: ["For each of these 300 brokers, give me the website and LinkedIn, nothing else.", "Here are 60 restaurant websites from my Austin sweep — which fit, and who's the owner?", "Re-qualify last week's delivery and get phone numbers for the good ones.", "Vet these 12 accounts from my spreadsheet against our criteria."],
    negative: ["Find me 10 new gyms in Texas.", "Qualify the top 10 leads in my batch.", "I have a CSV of 400 attendees to import."],
  },
  leadbay_refine_lead_targeting: {
    positive: ["Focus on hospitals that run their own IT in-house.", "Prioritize companies that have recently expanded headcount.", "On ne vend qu'au privé — arrête de me remonter des hôpitaux publics."],
    negative: ["Create a lens specialized in automobile.", "Add fintech to my Joinery lens.", "Show me my lenses.", "Exclude Groupe Solidum, we had an unpaid invoice with them."],
  },
  leadbay_remove_contact: {
    positive: ["Remove Jane Doe from that company — I added her by mistake.", "Delete this contact, it's the wrong person.", "Undo the contact I just added to Acme."],
    negative: ["Stop showing me this lead.", "Add a contact to this company.", "Show me today's leads."],
  },
  leadbay_remove_leads_from_campaign: {
    positive: ["Remove the Austin lead from my Q2 Push campaign.", "Take these 3 unqualified leads out of the Limoges Tour.", "Clean up campaign 1f12 — remove leads that bounced."],
    negative: ["Add the top 5 to my Q2 Push.", "Create a new campaign with these 9 leads.", "What campaigns do I have?"],
  },
  leadbay_report_friction: {
    positive: ["Report this to the Leadbay team — searching Wisconsin returns nothing.", "Yes, please let them know the enrichment came back empty.", "Can you flag to Leadbay that the region filter is wrong?"],
    negative: ["Ugh, this never finds what I'm looking for.", "I sent the intro email to Acme — log it.", "Thumbs down on this lead, wrong industry."],
  },
  leadbay_research_lead_by_id: {
    positive: ["Tell me everything about that lead I just picked.", "Is this one actually a fit — what does the AI think?"],
    negative: ["Look up Acme Corp for me.", "Show me today's leads."],
  },
  leadbay_research_lead_by_name_fuzzy: {
    positive: ["Look up Acme Corp for me.", "Find Initech in my pipeline.", "Who is Wink Lab? Their email is at @wink-lab.com."],
    negative: ["Tell me about that lead I just picked.", "Draft outreach to Acme's CTO.", "Websites and LinkedIn for these 200 companies."],
  },
  leadbay_scan_portfolio_signals: {
    positive: ["Which of my leads acquired a company since 2025?", "Scan my Lyon portfolio for funding signals.", "Find everyone in Monitor who changed CEO and build a campaign."],
    negative: ["Look up Acme Corp for me.", "Show me my follow-ups.", "Qualify my next 10 leads."],
  },
  leadbay_send_feedback: {
    positive: ["Send feedback to the team: the lead scores feel off this week.", "Can you tell Leadbay the onboarding was confusing?", "Tell Leadbay I'd love a way to schedule my morning check-in."],
    negative: ["Pulling leads in Lyon returns nothing — report that.", "Ugh, this never finds what I'm looking for. Show me today's leads.", "I emailed Acme — log that outreach."],
  },
  leadbay_set_lead_status: {
    positive: ["We just signed Acme Corp — mark them as won.", "Mark these three as lost, they went with a competitor.", "Add Northwind to my wanted list, they're a priority target."],
    negative: ["I emailed the CTO this morning, log it.", "Thumbs up on this one, show me more like it.", "Snooze this lead until next quarter."],
  },
  leadbay_set_qualification_questions: {
    positive: ["Our best customers are cold-storage plants that run their own maintenance crews — update my qualification for that.", "Écarte les sociétés en liquidation, je ne veux plus les voir.", "Remove the flooring question and add one about install crews."],
    negative: ["What qualification questions does Leadbay use?", "Add fintech to my Joinery lens.", "Exclude Groupe Solidum, we had an unpaid invoice with them."],
  },
  leadbay_set_telemetry: {
    positive: ["Turn off telemetry, I don't want my usage tracked.", "Re-enable analytics for my account.", "Is telemetry currently on for me?"],
    negative: ["I want to report a bug in the pull-leads tool.", "Send feedback to the Leadbay team.", "Why isn't my event showing up in PostHog?"],
  },
  leadbay_team_activity: {
    positive: ["How is my team doing this month?", "Who are my top performers in the last two weeks?", "Show me activity by rep."],
    negative: ["Show me today's leads.", "How is the Q3 Outbound campaign progressing?", "Which leads should I follow up with?"],
  },
  leadbay_tour_plan: {
    positive: ["I'm flying to Limoges in 4 days — give me 3 customers, 3 qualified prospects, and 3 new high-potential.", "I'm in San Francisco next Tuesday. Who's worth meeting?", "Plan my tour next Tuesday in Lyon: known accounts plus discoveries.", "Build a mixed itinerary for Berlin — I want both follow-ups and fresh leads.", "J'ai un rdv le 19 août à Colmar — trouve-moi les prospects dans un rayon de 10km."],
    negative: ["Show me my follow-ups for the SF trip.", "What's new in today's batch?", "Tell me about Acme Corp."],
  },
  leadbay_unpin_contact: {
    positive: ["Unpin Jane Doe — she's not the priority anymore.", "Remove the pin from that contact.", "Unfavourite this person."],
    negative: ["Pin this contact as priority.", "Remove that contact entirely.", "Add a new contact to this company."],
  },
  leadbay_update_contact: {
    positive: ["Update Jane's title to SVP Engineering.", "Fix this contact's LinkedIn URL.", "Change John's email to john@acme.com."],
    negative: ["Add a new contact to this company.", "Remove that contact, wrong person.", "Get me the email for this contact."],
  },
};
