// AUTO-GENERATED by @leadbay/promptforge — do not edit directly.
// Regenerate via: pnpm prompts:build
// Source-of-truth: packages/promptforge/{prompts,tool-descriptions}/*.md.tmpl

// Tool descriptions, alphabetized by frontmatter.name.

// region: leadbay_account_status
export const leadbay_account_status: string = `Show the user's account state — admin rights, language, last-active lens, current quota usage across daily/weekly/monthly windows for llm_completion / ai_rescore / web_fetch resources, and whether the org's intelligence is mid-regeneration. Quota windows also hint at the user's consumption pace: heavy recent activity (ai_rescore / web_fetch near their window limits) is a signal that Leadbay will deliver a larger fresh batch next time the user logs back in, since batch size is paced by real consumption.

WHEN TO USE: at the start of a session to know what the agent can/can't do, or after a 429 to explain to the user which resource window was exhausted and when it resets.

WHEN NOT TO USE: as a pre-flight gate before bulk ops — operations themselves return 429; this tool is for context, not gating.
`;
// endregion: leadbay_account_status

// region: leadbay_add_note
export const leadbay_add_note: string = `Add a note to a lead. Notes are visible to the whole organization in Leadbay.

WHEN TO USE: low-level — for free-form notes not tied to outreach actions, including meaningful per-lead notes/context preserved from an imported file after the import returns lead IDs.

WHEN NOT TO USE: to log an outreach action — use leadbay_report_outreach, which requires verification (gmail/calendar/user_confirmed) to prevent hallucinated outreach poisoning the SDR pipeline.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_add_note

// region: leadbay_adjust_audience
export const leadbay_adjust_audience: string = `Restrict (or expand) the lens audience by sector / size. Free-text sectors are auto-resolved against the sector taxonomy; ambiguous matches are surfaced to the agent rather than guessed silently. Permission routing is hidden: the default lens auto-clones to a new user lens; an org-level lens defaults to a per-user draft (admins can override with \`save_for_org:true\`). Filter MERGES with existing criteria (unrelated criteria are not dropped).

WHEN TO USE: when the user wants to see different kinds of leads (sector / size / etc.).

WHEN NOT TO USE: to refine BEYOND firmographics — that's leadbay_refine_prompt.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_adjust_audience

// region: leadbay_answer_clarification
export const leadbay_answer_clarification: string = `Answer the pending clarification question Leadbay raised after a refine_prompt. The answer is stored as the new \`user_prompt\` and triggers regeneration. Pass \`option_id\` (preferred — pick from the offered options) or \`text_answer\` (free-text). Admin-only.

WHEN TO USE: after leadbay_refine_prompt returns \`status='clarification_pending'\`.

WHEN NOT TO USE: to set a brand-new prompt — use leadbay_refine_prompt.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_answer_clarification

// region: leadbay_bulk_enrich_status
export const leadbay_bulk_enrich_status: string = `Check status + per-lead contacts for a bulk enrichment you previously launched via leadbay_enrich_titles. Returns the \`bulk_id\`, progress per lead (done/total enrichable contacts), and overall progress. When \`include_contacts=true\` (opt-in), includes each contact's email/phone/job_title/enrichment.done.

WHEN TO USE: poll this after leadbay_enrich_titles returns a \`bulk_id\`. Default \`include_contacts=false\` for cheap status polls; set \`include_contacts=true\` once \`all_done\` flips for the final read.

WHEN NOT TO USE: as a substitute for leadbay_research_lead — that already includes enriched contacts for a single lead.
`;
// endregion: leadbay_bulk_enrich_status

// region: leadbay_bulk_qualify_leads
export const leadbay_bulk_qualify_leads: string = `Pick the next N unqualified leads in the active lens and qualify them (run AI rescore + web fetch). Pass \`wait_for_completion:false\` to return quickly with \`{status:'running', qualify_id}\`; poll leadbay_qualify_status with that id. With \`wait_for_completion\` omitted/true, the legacy behavior polls until the answers are populated or a budget is exhausted. Already-qualified leads (those with a non-null \`ai_agent_lead_score\`) are silently no-ops on the backend, so this composite paginates past them to find fresh candidates. On 429 mid-fanout, stops launching but keeps polling already-launched leads.

**Default to \`wait_for_completion:false\`** for any \`count > 5\` or when chained inside a multi-phase workflow — the blocking default can hit the MCP per-call timeout and surface as \`"Request timed out"\` even when the server is still working fine. The async pattern (capture \`qualify_id\`, poll \`leadbay_qualify_status\` every ~10s) is timeout-proof. Reserve the blocking form for tiny single-digit counts in interactive use.

Context: Leadbay auto-qualifies roughly the top 10 of each daily batch. Leads below the top ~10 are NOT worse — the system is saving resources. This tool is how the agent spends more resources to go deeper on promising-looking leads the user hasn't had time to surface yet.

WHEN TO USE: when the user wants more qualified leads than what's currently shown, or when a lead looks promising in leadbay_pull_leads but has an empty \`qualification_summary\`.

WHEN NOT TO USE: to qualify a single specific lead — that's leadbay_qualify_lead (granular, advanced).

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_bulk_qualify_leads

// region: leadbay_clear_selection
export const leadbay_clear_selection: string = `Clear the user's transient selection.

WHEN TO USE: cleanup after manual selection work, or recovery from a stuck composite.

WHEN NOT TO USE: in normal flow — composites clear in their own finally blocks.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_clear_selection

// region: leadbay_clear_user_prompt
export const leadbay_clear_user_prompt: string = `Remove the org's intelligence-refinement prompt (revert to AI-only generation). Admin-only. Triggers full intelligence regeneration.

WHEN TO USE: when a refinement turned out to be the wrong direction.

WHEN NOT TO USE: to replace with a different prompt — just call leadbay_refine_prompt; that overwrites.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_clear_user_prompt

// region: leadbay_create_custom_field
export const leadbay_create_custom_field: string = `Create an org-level CRM custom field for imports, then use the returned \`mapping_value\` in leadbay_import_leads / leadbay_import_and_qualify mappings. Use when the user's file contains valuable columns that do not fit Leadbay's standard fields, such as source-system deep links, source record IDs, campaign provenance, or user-requested enrichment attributes.

For HubSpot record links, prefer \`type:'EXTERNAL_ID'\` with \`config.url_template\` and import only the stable HubSpot id as the CSV value. Example: create field name 'HubSpot Contact', type 'EXTERNAL_ID', config \`{url_template:'https://app.hubspot.com/contacts/<portal-id>/record/0-1/{value}'}\`; then map \`hubspot_id\` to the returned \`mapping_value\`. If only a full URL column exists and the id cannot be safely extracted, use a TEXT field instead.

WHEN TO USE: after leadbay_list_mappable_fields shows no suitable existing custom field and preserving the column matters to the user's goal.

WHEN NOT TO USE: for standard company/contact data that maps to LEAD_WEBSITE, LEAD_NAME, CONTACT_EMAIL, etc.; do not create custom fields for noisy scraper notes unless the user explicitly asks to preserve them.
`;
// endregion: leadbay_create_custom_field

// region: leadbay_create_lens
export const leadbay_create_lens: string = `Create a new user-level lens by cloning an existing lens's filter/scoring as the starting point.

WHEN TO USE: when adjust_audience determined the current lens cannot be edited (e.g. it's the org default).

WHEN NOT TO USE: to update an existing lens — use leadbay_update_lens or leadbay_update_lens_filter.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_create_lens

// region: leadbay_create_lens_draft
export const leadbay_create_lens_draft: string = `Create (or fetch existing) draft of an org-level lens. Idempotent — same user calling twice returns the same draft. The returned lens has \`draft_of\` set to the original lens id.

WHEN TO USE: when a non-admin needs to modify an org-level lens — make a draft, edit the draft.

WHEN NOT TO USE: from agent flow — leadbay_adjust_audience handles the draft-routing transparently.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_create_lens_draft

// region: leadbay_deselect_leads
export const leadbay_deselect_leads: string = `Remove leads from the user's transient selection.

WHEN TO USE: when narrowing a previously-built selection without clearing it entirely.

WHEN NOT TO USE: in normal flow — leadbay_enrich_titles handles selection lifecycle.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_deselect_leads

// region: leadbay_discover_leads
export const leadbay_discover_leads: string = `Get AI-recommended leads from Leadbay. Returns paginated lead summaries with scores, AI summaries, tags, and recommended contacts. Auto-resolves to the active lens if \`lensId\` is omitted; \`count\` is capped at 50 per page.

WHEN TO USE: low-level — when you need raw paginated wishlist access without the qualification_summary attached by leadbay_pull_leads.

WHEN NOT TO USE: as the agent's default lead-discovery entry point — use leadbay_pull_leads, which adds a one-line qualification summary per lead.
`;
// endregion: leadbay_discover_leads

// region: leadbay_dismiss_clarification
export const leadbay_dismiss_clarification: string = `Dismiss the pending clarification without answering. Leadbay proceeds with its best guess. Admin-only.

WHEN TO USE: when the user explicitly doesn't want to answer the disambiguation.

WHEN NOT TO USE: as a default — answering with even a free-text reason gives Leadbay better signal.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_dismiss_clarification

// region: leadbay_enrich_contacts
export const leadbay_enrich_contacts: string = `Order email and/or phone enrichment for a specific contact. Performs an advisory credit check, then tries the paid-contact path and falls back to the org-contact path on NOT_FOUND. Consumes enrichment credits.

WHEN TO USE: when you have a specific \`contact_id\` (from leadbay_get_contacts) and want to enrich just that one.

WHEN NOT TO USE: for bulk enrichment by job title across many leads — use leadbay_enrich_titles, which handles the selection lifecycle and returns a clean preview/launch flow.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_enrich_contacts

// region: leadbay_enrich_titles
export const leadbay_enrich_titles: string = `Order contact enrichments by job title across many leads. Contacts are NOT returned by default with a lead (Leadbay keeps enrichment out-of-band to control cost); the agent requests them on demand via this tool when it's ready to actually reach out. Two modes: (A) NO \`titles\` param — returns the available titles + Leadbay's \`title_suggestions\` + \`auto_included_titles\` + a count of enrichable contacts, so the agent can ask the user which titles to enrich. (B) \`titles\` given — calls preview, then launches if there's anything enrichable. On 429 returns \`{status:'quota_exceeded'}\` cleanly. Selection lifecycle is wrapped in a try/finally so the user's selection is left clean even on error.

WHEN TO USE: as the agent's go-to enrichment entry point, immediately before proposing outreach.

WHEN NOT TO USE: to enrich a single contact — that's leadbay_enrich_contacts (granular). Speculatively, before the user has committed to outreaching — enrichment spends credits.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_enrich_titles

// region: leadbay_get_clarification
export const leadbay_get_clarification: string = `Check whether Leadbay has a pending clarification question — a question raised when refining the intelligence prompt produced contradictory or ambiguous criteria. Returns \`{pending: false, clarification: null}\` when nothing is pending (the backend returns 204).

WHEN TO USE: after leadbay_refine_prompt, to see if Leadbay needs the user to disambiguate.

WHEN NOT TO USE: to answer the question — use leadbay_answer_clarification.
`;
// endregion: leadbay_get_clarification

// region: leadbay_get_contacts
export const leadbay_get_contacts: string = `Get contacts for a lead, including enriched email and phone data. Returns both organization contacts and enrichable contacts with IDs, tagged with \`source:'org'|'paid'\`.

WHEN TO USE: to check enrichment status (\`contact.enrichment.done\`) on individual leads after a bulk enrichment was launched, or to find the \`contact_id\` needed by leadbay_enrich_contacts.

WHEN NOT TO USE: as a substitute for leadbay_research_lead, which already includes enriched contacts in its return.
`;
// endregion: leadbay_get_contacts

// region: leadbay_get_enrichment_job_titles
export const leadbay_get_enrichment_job_titles: string = `List the actual job titles present across the leads currently in the user's selection — the candidate set the user can ask to enrich.

WHEN TO USE: after leadbay_select_leads, to know which titles are even available before launching a bulk enrichment.

WHEN NOT TO USE: standalone — the selection must already be populated, otherwise the result is an empty array. leadbay_enrich_titles wraps this whole flow when you don't need to inspect the title list manually.
`;
// endregion: leadbay_get_enrichment_job_titles

// region: leadbay_get_epilogue_responses
export const leadbay_get_epilogue_responses: string = `Read the lead's epilogue history — what status (still chasing, meeting booked, etc.) was set when, and by whom. Paginated (\`count\` 1-200 default 20, \`page\` 0-indexed).

WHEN TO USE: to see the lead's outreach progression before deciding the next step.

WHEN NOT TO USE: when the lead summary's \`epilogue_actions_count\` is 0.
`;
// endregion: leadbay_get_epilogue_responses

// region: leadbay_get_lead_activities
export const leadbay_get_lead_activities: string = `Get prospecting activity history for a lead (emails sent, calls made, status changes, notes). Each entry is \`{type, date}\`; older activities are trimmed by \`count\` (max 100, default 50).

WHEN TO USE: to avoid redundant outreach and understand where this lead is in the sales process.

WHEN NOT TO USE: when leadbay_research_lead has already been called — it includes recent prospecting actions in its engagement block.
`;
// endregion: leadbay_get_lead_activities

// region: leadbay_get_lead_notes
export const leadbay_get_lead_notes: string = `Read existing notes on a lead — context the human team or prior agent runs have already captured.

WHEN TO USE: before adding a note via leadbay_report_outreach, to avoid duplicating or overwriting context the SDR already wrote.

WHEN NOT TO USE: when the lead summary's \`notes_count\` is 0 — there's nothing to fetch.
`;
// endregion: leadbay_get_lead_notes

// region: leadbay_get_lead_profile
export const leadbay_get_lead_profile: string = `Get a full lead profile including company details, AI qualification scores, web insights, and contacts. Also marks the lead as SEEN+CLICKED in the user's lens so it ages out of the "new" Discover view (fire-and-forget; profile fetch never blocks on it).

WHEN TO USE: low-level — for fine-grained access to the raw shape of the lead profile.

WHEN NOT TO USE: as the agent's default lead-detail tool — use leadbay_research_lead, which structures the data top-down (qualification first, then signals, then firmographics, then contacts, then engagement) and reshapes web_fetch.content into a stable array form.
`;
// endregion: leadbay_get_lead_profile

// region: leadbay_get_lens_filter
export const leadbay_get_lens_filter: string = `Read the firmographic filter (sectors, sizes, locations) currently applied to a lens.

WHEN TO USE: before adjusting an audience — see what's already restricted so changes are diffs, not full replacements.

WHEN NOT TO USE: to actually apply changes — use the leadbay_adjust_audience composite, which handles permissions transparently.
`;
// endregion: leadbay_get_lens_filter

// region: leadbay_get_lens_scoring
export const leadbay_get_lens_scoring: string = `Read the AI-scoring criteria configured on a lens (what makes a lead score 100 vs 30).

WHEN TO USE: when explaining why a lead got the score it did.

WHEN NOT TO USE: to mutate scoring — that's an admin/setup operation, not part of the agent loop.
`;
// endregion: leadbay_get_lens_scoring

// region: leadbay_get_prospecting_actions
export const leadbay_get_prospecting_actions: string = `Read the CRM-style activity log for a lead (calls, emails, meetings — actions performed by humans or prior agent runs). Paginated (\`count\` 1-200 default 20, \`page\` 0-indexed).

WHEN TO USE: before contacting the lead, to avoid duplicating outreach the team already did.

WHEN NOT TO USE: when the lead summary's \`prospecting_actions_count\` is 0.
`;
// endregion: leadbay_get_prospecting_actions

// region: leadbay_get_quota
export const leadbay_get_quota: string = `Read remaining quota / spend across daily, weekly, and monthly windows for the org's resources (\`llm_completion\`, \`ai_rescore\`, \`web_fetch\`). Each entry shows \`current_units\` vs \`max_units\` and \`resets_at\`.

WHEN TO USE: after a 429 error, to explain to the user which window was hit and when it resets.

WHEN NOT TO USE: as a pre-flight gate before bulk operations — operations themselves return 429 with hints; this tool is for diagnostics, not gating.
`;
// endregion: leadbay_get_quota

// region: leadbay_get_selection_ids
export const leadbay_get_selection_ids: string = `List the lead ids currently in the user's selection (the transient set that bulk operations like enrichment act on).

WHEN TO USE: to verify the selection state before/after bulk ops if a composite call has misbehaved.

WHEN NOT TO USE: in the normal flow — leadbay_enrich_titles manages selection lifecycle automatically (select → action → clear).
`;
// endregion: leadbay_get_selection_ids

// region: leadbay_get_taste_profile
export const leadbay_get_taste_profile: string = `Get the user's Ideal Buyer Profile, purchase-intent tags, and qualification questions. The result is cached on the client. Returns an operator \`hint\` when no profile is configured yet.

WHEN TO USE: at the very start of a session to understand what kind of leads the user is looking for.

WHEN NOT TO USE: per-lead — leadbay_research_lead already includes the per-lead qualification answers (which are scored against these org-level questions).
`;
// endregion: leadbay_get_taste_profile

// region: leadbay_get_user_prompt
export const leadbay_get_user_prompt: string = `Read the org's intelligence-refinement prompt (free-text instruction that steers lead recommendations beyond firmographics). Returns \`{prompt: null, set: false}\` when none is configured (the backend returns 204 in that case).

WHEN TO USE: to know what's currently steering the agent's recommendations before suggesting a refine.

WHEN NOT TO USE: to set/change the prompt — use leadbay_refine_prompt.
`;
// endregion: leadbay_get_user_prompt

// region: leadbay_get_web_fetch
export const leadbay_get_web_fetch: string = `Read the AI-generated web-research summary for a lead — company profile, business signals, prospecting clues, each with sources and "hot" flags marking high-signal recent items. The content is dictioned by emoji-prefixed section labels in the raw API.

WHEN TO USE: when the agent already qualified this lead and wants the underlying research to reason from.

WHEN NOT TO USE: as the first read on a lead — the leadbay_research_lead composite bundles this with qualification answers and reshapes the dict into a stable array form.
`;
// endregion: leadbay_get_web_fetch

// region: leadbay_import_and_qualify
export const leadbay_import_and_qualify: string = `Import + qualify leads in one call. Pass either \`domains: [{domain, name?}]\` (Mode A) OR \`records[]\` with \`mappings\` (Mode B). At least one mapped field must be LEADBAY_ID, CRM_ID, SIREN, LEAD_NAME, or LEAD_WEBSITE. Discover the org's mappable surface via \`leadbay_list_mappable_fields\`. For messy files, prefer the \`leadbay_import_file\` prompt which walks an agent through scan → resolve → preserve → commit phases.

WHEN TO USE: agent has a list of companies (domains, or CSV-shaped rows from the user's CRM) and wants the full AI qualification — qualification answers, web-research signals — without orchestrating import + bulk_qualify_leads + lead_profile chains by hand.

WHEN NOT TO USE: discovery (use leadbay_pull_leads); single-lead deep dive (use leadbay_research_lead); high-cadence or untrusted automation — this mutates user state and consumes ai_rescore + web_fetch quota.

Budgets: \`total_budget_ms\` caps wall-clock; \`per_lead_budget_ms\` caps each lead's poll. For short transport timeouts, pass \`wait_for_completion:false\` and poll \`leadbay_import_status\`. Outputs \`qualified[]\`, \`still_running[]\`, \`not_imported[]\`, \`qualify_id\` (resumable handle). Idempotent within a 5-min window. \`dry_run:'preview'\` returns mapping hints + custom-field candidates without importing.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.


Requires: LEADBAY_MCP_WRITE=1 (MCP) or exposeWrite=true (OpenClaw); admin role; active billing. Imported leads are NOT auto-promoted to the Monitor view; lens-scoring threshold decides.
`;
// endregion: leadbay_import_and_qualify

// region: leadbay_import_leads
export const leadbay_import_leads: string = `Import leads into Leadbay's CRM via the file-import wizard. Returns stable Leadbay leadIds for downstream chaining into leadbay_bulk_qualify_leads / leadbay_research_lead. For MCP clients with short transport timeouts, pass \`wait_for_completion:false\` to return quickly with \`{status:'running', handle_id}\`; poll leadbay_import_status with that handle. For end-to-end import+qualify in one call, prefer leadbay_import_and_qualify. For messy files, prefer the \`leadbay_import_file\` prompt which walks an agent through scan → resolve → preserve → commit phases.

TWO MODES: (A) Domain-list shortcut — pass \`domains: [{domain, name?}]\`. The tool builds a 2-column CSV (LEAD_NAME, LEAD_WEBSITE) and imports with the default mapping. (B) Custom records + mapping — pass \`records: [{Col1, Col2, ...}]\` plus \`mappings.fields: {Col1: 'LEAD_NAME', ...}\`. \`mappings.fields\` must include LEADBAY_ID, CRM_ID, SIREN, LEAD_NAME, or LEAD_WEBSITE (resolver needs at least one identity key). Pass exactly one of \`domains\` / \`records\`. Reserved column \`MCP_ROW_ID\` cannot appear in records/mappings — the tool injects it for stable reconciliation.

MUTATES USER STATE: each call creates a row in the user's CRM-imports list (visible in the web UI) and touches onboarding state. Suitable for occasional automation, NOT for high-cadence (>5 calls/day). Imported leads are NOT auto-promoted to the user's Monitor view; lens-scoring threshold decides. For messy files call leadbay_resolve_import_rows first, then pass \`records_for_import\`/\`mappings_for_import\` here. Agents should inspect every column, build a preservation plan, and pass an explicit final mapping. For each meaningful column decide standard field, CONTACT_* field, Leadbay note, custom field, derived helper, or skip with a reason. For contact-only exports, derive a company-domain column from CONTACT_EMAIL only when it's a real business domain. Multiple rows can share the same LEADBAY_ID and import as separate contacts on that lead. Custom fields use \`CUSTOM.<id>\` in \`mappings.fields\` or the \`mappings.custom_fields\` shorthand. For source-system deep links create a custom field via leadbay_create_custom_field first (prefer EXTERNAL_ID + url_template). Preserve meaningful per-lead notes by calling leadbay_add_note after import returns lead IDs.

WHEN TO USE: you have a list of company domains from another system (CRM, analytics, email correspondents) and need stable Leadbay leadIds; or CRM-shaped rows with custom columns and want to drive the wizard with explicit field mappings.

WHEN NOT TO USE: for prospect discovery (use leadbay_pull_leads); for one specific company's profile (use leadbay_research_company); when you can't tolerate the side effects above; when you also want qualification in the same call (use leadbay_import_and_qualify).

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.


Requires: LEADBAY_MCP_WRITE=1 (MCP) or exposeWrite=true (OpenClaw); admin role on the Leadbay account; active billing.
`;
// endregion: leadbay_import_leads

// region: leadbay_import_status
export const leadbay_import_status: string = `Retrieve the current state of an async lead import. Pass \`handle_id\` returned by \`leadbay_import_leads({wait_for_completion:false})\`, or pass legacy \`importIds[]\` to inspect backend wizard rows. This status call performs a single refresh pass and never polls in a loop.

WHEN TO USE: after leadbay_import_leads or leadbay_import_and_qualify returns \`{status:'running', handle_id}\` for the import phase, call this tool later to retrieve progress or the final import result without re-running the import.

WHEN NOT TO USE: for qualification handles returned as \`qualify_id\` — use leadbay_qualify_status for those; or when you still want the legacy blocking behavior from leadbay_import_leads with \`wait_for_completion=true\`.
`;
// endregion: leadbay_import_status

// region: leadbay_launch_bulk_enrichment
export const leadbay_launch_bulk_enrichment: string = `Launch a bulk-enrichment job against the current selection. The backend requires \`email=true\` OR \`phone=true\` (both can be true). Returns 204 with no body — there is no bulk_id and no per-job status endpoint. Track results by polling individual leads via leadbay_get_contacts after ~60s; \`contact.enrichment.done\` flips to true. \`dry_run:true\` returns the call shape without contacting the backend.

WHEN TO USE: low-level.

WHEN NOT TO USE: from agent flow — leadbay_enrich_titles handles selection lifecycle, preview, launch, and cleanup.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_launch_bulk_enrichment

// region: leadbay_list_lenses
export const leadbay_list_lenses: string = `List all available Leadbay lenses (saved lead-search configurations). Each lens defines a different target market or buyer segment. The lens with \`is_last_active=true\` is used by default for lead discovery.

WHEN TO USE: when the user wants to switch lens or asks "what lenses do I have".

WHEN NOT TO USE: in normal flow — composites auto-resolve the active lens via \`/me.last_requested_lens\`.
`;
// endregion: leadbay_list_lenses

// region: leadbay_list_mappable_fields
export const leadbay_list_mappable_fields: string = `List every CRM field the agent can target when calling leadbay_import_leads or leadbay_import_and_qualify. Returns two arrays: \`standard_fields\` (Leadbay's built-in StandardCrmFieldType enum — LEAD_NAME, LEAD_WEBSITE, LEAD_STATUS, contact + location + sector fields) and \`custom_fields\` (this org's user-defined fields — id, name, type, and the literal \`mapping_value\` you pass in \`mappings.fields\`). For custom fields, \`mapping_value\` is the wire-format string \`CUSTOM.<id>\` — pass it verbatim.

For contact exports, map person data to CONTACT_* fields and still provide parent-company identity via LEADBAY_ID/LEAD_WEBSITE/LEAD_NAME/CRM_ID/SIREN. When contact emails contain business domains, agents may derive a clean company-domain column for LEAD_WEBSITE only when the domain agrees with the row's company/deal/brand context, while preserving the original email as CONTACT_EMAIL. For import files, audit every meaningful source column. If no standard/contact field fits, preserve the data by creating or reusing a custom field unless the column is blank, duplicate plumbing, raw unparsed noise after useful extraction, or harmful to data quality. For HubSpot or other source-system deep links, create or reuse an EXTERNAL_ID/TEXT custom field with leadbay_create_custom_field, then map the source id/link to the returned \`mapping_value\`. Backend mapping_hints are advisory only; for contact files, do not accept hints such as first_name -> LEAD_NAME when the column is clearly a person field.

Optional \`for_records\` param: pass a sample of CSV-shaped rows and the tool also runs the wizard's preprocess on them, attaching \`mapping_hints\` (per-column AI-confidence suggestions) and \`custom_field_candidates\` (custom fields that match unmapped columns by exact / case-insensitive / fuzzy name). Saves a separate preview round-trip.

WHEN TO USE: before authoring an import mapping, especially when the CSV has columns that aren't obvious matches for standard fields.

WHEN NOT TO USE: when you already know the mapping — this call is cheap (~50ms without for_records, ~5–10s with) but unnecessary if the agent has already cached the catalog within the same conversation.
`;
// endregion: leadbay_list_mappable_fields

// region: leadbay_list_sectors
export const leadbay_list_sectors: string = `List the sector taxonomy (id + display name in the requested language). Default: \`lang\` follows the caller's language; \`includeInvisible=false\` returns ~1,091 visible sectors.

WHEN TO USE: to resolve a free-text sector name (e.g. "Healthcare") into the sector ids that leadbay_adjust_audience needs.

WHEN NOT TO USE: when you already have sector ids — pass them directly.
`;
// endregion: leadbay_list_sectors

// region: leadbay_login
export const leadbay_login: string = `Log in to Leadbay with email and password. Auto-detects region (us|fr) — the user does not need to know which backend their account lives on. On success, sets the client's bearer token and switches the active region if needed.

WHEN TO USE: at the start of a session if no token is preconfigured (cfg.token / LEADBAY_TOKEN).

WHEN NOT TO USE: if a token is already preconfigured — you'll just overwrite it. The user needs a Leadbay account first; they can register at https://wow.leadbay.ai/?register=true.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_login

// region: leadbay_pick_clarification
export const leadbay_pick_clarification: string = `Answer the pending clarification question — either by picking one of the offered options (\`option_id\`) or by typing a free-text answer. The answer is stored as the new user_prompt and triggers regeneration. Admin-only.

WHEN TO USE: low-level.

WHEN NOT TO USE: from agent flow — use leadbay_answer_clarification.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_pick_clarification

// region: leadbay_prepare_outreach
export const leadbay_prepare_outreach: string = `Prepare an outreach package for a single lead: recommended contact + enriched contact details + AI summary. Optionally trigger contact enrichment in-flight (\`enrich:true\`); enrichment is async, so poll leadbay_get_contacts after ~60s if you need the result inline.

WHEN TO USE: when the agent is about to draft outreach for ONE specific lead and needs the contact's email/phone.

WHEN NOT TO USE: across many leads — use leadbay_enrich_titles for bulk; for general lead detail use leadbay_research_lead (richer signals); to actually log the outreach action use leadbay_report_outreach (requires verification).
`;
// endregion: leadbay_prepare_outreach

// region: leadbay_preview_bulk_enrichment
export const leadbay_preview_bulk_enrichment: string = `Preview a bulk-enrichment cost given a set of job titles applied to the current selection. Returns \`{selected_leads, enriched_contacts, enrichable_contacts, title_suggestions, auto_included_titles, previously_enriched_titles}\`. \`previously_enriched_titles\` is a newer field (in prod soon) — when present, the agent can recommend repeating those titles for new leads.

WHEN TO USE: between selecting leads and launching, to know what the enrichment will cost.

WHEN NOT TO USE: from agent flow — leadbay_enrich_titles wraps preview + launch with the right safety checks.
`;
// endregion: leadbay_preview_bulk_enrichment

// region: leadbay_promote_lens
export const leadbay_promote_lens: string = `Promote a user-level lens (or draft) to org-level so all teammates see it. Admin-only.

WHEN TO USE: rare — when an admin user has built a lens (or refined a draft) and wants to share it org-wide.

WHEN NOT TO USE: as a non-admin (will fail with 403); for personal lens changes (those stay user-scoped).

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_promote_lens

// region: leadbay_pull_leads
export const leadbay_pull_leads: string = `Pull up new leads from the user's last-active lens — the canonical "show me today's prospects" tool. Leadbay works like an inbox: each time the user logs back in, a fresh batch is delivered, paced by how many leads they've actually acted on recently. Pulling more won't produce more; user outreach/skips/saves does. Each returned lead carries a one-line \`qualification_summary\` built from leadbay_ai_agent_responses, plus the rich tags / scores / recommended_contact_title / engagement counters / in-flight flags from the lead summary.

Roughly the top 10 of the batch come pre-qualified (populated qualification_summary + ai_agent_lead_score); leads below the top ~10 carry only the basic firmographic \`score\` — not worse, just resource-saved by the system. Call leadbay_bulk_qualify_leads to deepen any of them on demand.

WHEN TO USE: as the agent's default opening move when the user wants to see leads, or as a daily check-in for what's new today.

WHEN NOT TO USE: when the user has named a specific lens — pass \`lensId\` to override the auto-resolution. Replaces the older leadbay_find_prospects (removed in v0.2.0).

The active lens can change between calls (5-min cache + backend \`last_requested_lens\`). If a multi-step workflow depends on staying on one lens, **capture \`lensId\` from the first response and pass it explicitly to every subsequent Leadbay call** — including re-pulls, bulk qualifies, and research. Re-pulling without \`lensId\` after a long-running tool may silently switch to a different lens and discard prior work.
`;
// endregion: leadbay_pull_leads

// region: leadbay_qualify_lead
export const leadbay_qualify_lead: string = `Trigger AI qualification for a single lead (web fetch + AI rescore). The operation is asynchronous — results take ~60s. \`forceFetch:true\` re-runs even if recent data exists.

WHEN TO USE: low-level — when you need to kick qualification on exactly one lead without composite orchestration.

WHEN NOT TO USE: as the agent's bulk-qualify path — use leadbay_bulk_qualify_leads, which paginates past already-qualified leads, fans out, polls, and bails out cleanly on 429.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_qualify_lead

// region: leadbay_qualify_status
export const leadbay_qualify_status: string = `Retrieve the current state of an import_and_qualify (or bulk_qualify_leads) launch by \`qualify_id\`. Returns the same \`qualified[]\` / \`still_running[]\` shape as the original composite, refreshed against the backend at call time. The handle is persisted to \`~/.leadbay/bulks.json\` with a 30-day TTL and survives MCP restart.

WHEN TO USE: after leadbay_import_and_qualify or leadbay_bulk_qualify_leads returned a \`qualify_id\` with non-empty \`still_running[]\`, call this tool a few minutes later (or hours) to retrieve the now-completed qualifications without re-running the import or re-spending qualify quota.

WHEN NOT TO USE: as a substitute for leadbay_research_lead — that's a deeper per-lead profile and includes contacts. This tool is purely the qualification answers + signals_count.
`;
// endregion: leadbay_qualify_status

// region: leadbay_recall_ordered_titles
export const leadbay_recall_ordered_titles: string = `Show job titles the org has previously enriched, so the agent can repeat the same titles for new leads (or skip already-saturated ones). Two implementation paths: (1) PREFERRED — a selection-scoped preview call that reads \`previously_enriched_titles\` from the backend (newer prod field). (2) FALLBACK — live aggregation across each lead's enriched contacts. The composite picks transparently.

WHEN TO USE: before leadbay_enrich_titles, to plan which titles to order.

WHEN NOT TO USE: when you already know the exact titles you want to enrich.
`;
// endregion: leadbay_recall_ordered_titles

// region: leadbay_refine_prompt
export const leadbay_refine_prompt: string = `Refine the kind of leads Leadbay surfaces, beyond firmographics. Free-text instruction (e.g. "focus on hospitals running their own IT"). Sets the org's \`user_prompt\`; if the new prompt produces ambiguous criteria, Leadbay raises a clarification question, which this composite polls for and surfaces. Admin-only on the backend (will return 403 for non-admins).

WHEN TO USE: when audience filters (leadbay_adjust_audience) aren't enough.

WHEN NOT TO USE: to answer a pending clarification — that's leadbay_answer_clarification.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_refine_prompt

// region: leadbay_remove_epilogue
export const leadbay_remove_epilogue: string = `Bulk-clear the epilogue status from a set of leads.

WHEN TO USE: when an outreach action was logged in error and needs to be undone.

WHEN NOT TO USE: to change status — call leadbay_set_epilogue_status with the new status (it overwrites).

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_remove_epilogue

// region: leadbay_report_outreach
export const leadbay_report_outreach: string = `Log an outreach action (email, call, message, meeting) on a lead so the human team using Leadbay sees the progress in their UI. Writes a NOTE on the lead and (optionally) sets an EPILOGUE status (still chasing, meeting booked, etc.). Bulk variant: pass \`lead_ids=[uuid,...]\` instead of \`lead_id\` (epilogue is bulk-native; notes fan out per-lead).

VERIFICATION REQUIRED: every call must include \`verification={source: 'gmail_message_id'|'calendar_event_id'|'user_confirmed', ref: '<id-or-confirmation>'}\` to prevent hallucinated outreach poisoning the pipeline. The verification is appended to the note body. Skipping or fabricating verification poisons the human team's pipeline.

WHEN TO USE: AFTER actually emailing/calling/meeting/messaging a contact, OR after a substantive decision the user wants logged (skip, save, hand off).

WHEN NOT TO USE: BEFORE doing the outreach (use \`dry_run:true\` to validate args first); without verification (call will be rejected); from a flow where the user did not consent to having actions logged automatically.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_report_outreach

// region: leadbay_research_company
export const leadbay_research_company: string = `Deep-dive research on a specific company by NAME (fuzzy match against the active lens's wishlist). Pass \`companyName\` (matches the top-scoring lead with that name) or \`leadId\` (takes precedence when both supplied).

WHEN TO USE: when the user references a company by name and you don't yet have its \`lead_id\`.

WHEN NOT TO USE: when you already have the lead_id — use leadbay_research_lead directly (it bundles richer signals + better top-down ordering for the agent).
`;
// endregion: leadbay_research_company

// region: leadbay_research_lead
export const leadbay_research_lead: string = `Tell me everything decision-relevant about a single lead. Bundles the lens-scoped lead profile, the AI qualification answers (the agent's knowledge-base food), the structured web-research signals (with hot flags + sources), the enriched contacts, and the recent notes/epilogue/prospecting activity in one call. Order is deliberate: qualification first, then signals, then firmographics, then contacts, then engagement.

Scoring has two layers: the basic \`score\` (firmographic, always present, already decent) and the AI qualification layer (\`ai_agent_lead_score\` + per-question answers + web_fetch signals). The AI layer is pre-populated for roughly the top 10 of each daily batch, and on-demand (via leadbay_bulk_qualify_leads) for anything below that. Combine both layers when judging a lead.

WHEN TO USE: when picking up a single lead from leadbay_pull_leads to decide whether to act on it.

WHEN NOT TO USE: across many leads at once — that's leadbay_pull_leads' job. (This composite supersedes the lower-level leadbay_get_lead_profile in agent flow; the granular tool stays available for fine-grained access.)

**Concurrency note**: this is a composite that reads many sub-resources per call. Call it **sequentially** or in small batches (≤3 parallel) when researching multiple leads. Firing 10+ in parallel can saturate the transport and produce misleading \`"Tool permission stream closed"\` errors that look like permission failures but are really backpressure. On a transient stream/timeout failure, retry the same lead once before moving on.
`;
// endregion: leadbay_research_lead

// region: leadbay_resolve_import_rows
export const leadbay_resolve_import_rows: string = `Resolve messy CSV-shaped lead rows against Leadbay before file import. The tool sends each row's available identity signals to \`POST /leads/resolve\`, returns matched lead IDs or ambiguous candidate IDs, and produces \`records_for_import\` plus a SAFE identity-only \`mappings_for_import\` starting point for leadbay_import_leads / leadbay_import_and_qualify. This tool deliberately does not try to understand every CSV dialect; the agent should inspect the file, derive clean helper columns when useful, pass explicit \`identity_mappings\`, and build the final CRM mapping from \`mapping_guidance\`.

WHEN TO USE: before importing user-supplied files when domains, names, CRM IDs, registry numbers, or Leadbay IDs may be inconsistently formatted; when the agent needs to pre-resolve messy rows, inspect ambiguous candidates, or prepare LEADBAY_ID values for the import composites. For contact-only files, first derive company website/domain from business contact emails where possible, while ignoring consumer mailbox domains. Deterministic matches get a LEADBAY_ID column inserted so the standard import commits immediately. Ambiguous rows are deliberately left without LEADBAY_ID; inspect candidates and choose one only when the evidence is good. Rows with websites but no match can still be imported; Leadbay may crawl and match them later, and leadbay_import_status can surface late matches.

WHEN NOT TO USE: for prospect discovery from scratch (use leadbay_pull_leads); for one known company profile (use leadbay_research_company / leadbay_research_lead); or when the file already has clean, final LEADBAY_ID/CRM_ID/SIREN mappings and no row-level identity disambiguation is needed.
`;
// endregion: leadbay_resolve_import_rows

// region: leadbay_select_leads
export const leadbay_select_leads: string = `Add leads to the user's transient selection (used by selection-scoped bulk operations). Accepts 1-1000 \`leadIds\` per call.

WHEN TO USE: low-level. The user's selection is a per-token global state — be careful when invoking directly.

WHEN NOT TO USE: in normal flow — leadbay_enrich_titles wraps select → action → clear in one call with proper Mutex protection. Calling this directly without acquiring the selection lock can clobber concurrent composite calls.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_select_leads

// region: leadbay_set_active_lens
export const leadbay_set_active_lens: string = `Mark a lens as last-used. Subsequent \`/me\` reads return it as \`last_requested_lens\`, so all composite tools default to it.

WHEN TO USE: after the user explicitly switched contexts (e.g. created a new lens via leadbay_create_lens).

WHEN NOT TO USE: in normal flow — leadbay_pull_leads and leadbay_adjust_audience auto-set the right lens.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_set_active_lens

// region: leadbay_set_epilogue_status
export const leadbay_set_epilogue_status: string = `Bulk-set the outreach progress (epilogue) status across a set of leads. Status values: \`STILL_CHASING\`, \`COULD_NOT_REACH_STILL_TRYING\`, \`INTEREST_VALIDATED_OR_MEETING_PLANED\` ("meeting booked"), \`NOT_INTERESTED_LOST\` (short labels accepted; mapped to the \`EPILOGUE_*\` enum). Up to 1000 leads per call.

WHEN TO USE: low-level.

WHEN NOT TO USE: from agent flow — leadbay_report_outreach pairs this with a note + verification, which is what humans actually need to see in Leadbay.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_set_epilogue_status

// region: leadbay_set_user_prompt
export const leadbay_set_user_prompt: string = `Set the org's intelligence-refinement prompt — free-text instruction that steers Leadbay's lead recommendations beyond firmographics. Admin-only. Setting this clears any pending clarification and triggers a full intelligence regeneration (web search + high-reasoning). \`dry_run:true\` returns the call shape without contacting the backend.

WHEN TO USE: low-level.

WHEN NOT TO USE: from agent flow — use leadbay_refine_prompt, which polls for follow-up clarifications.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_set_user_prompt

// region: leadbay_update_lens
export const leadbay_update_lens: string = `Update lens metadata (name, description, mode flags). Does NOT change the audience filter — use leadbay_update_lens_filter for that.

WHEN TO USE: rename a lens or toggle \`multi_product_mode\` / \`use_hq_only\`.

WHEN NOT TO USE: to change which leads the lens shows — that's a filter operation.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_update_lens

// region: leadbay_update_lens_filter
export const leadbay_update_lens_filter: string = `Replace the audience filter (sectors, sizes, locations) on a lens. Body is the full \`Filter\` object — this is a REPLACE, not a merge. Returns 400 \`default_lens\` if applied to the org default lens (clone it first). \`dry_run:true\` returns the call shape without contacting the backend.

WHEN TO USE: low-level mutation when you've already prepared the merged filter.

WHEN NOT TO USE: from agent flow — use leadbay_adjust_audience, which handles draft-vs-direct routing, permission fallback, and the merge logic so unrelated criteria aren't dropped.

This tool MUTATES state. The caller (agent or human-in-the-loop) is responsible for confirming intent before invocation; the MCP server does not soft-prompt for confirmation. See \`annotations.destructiveHint\`.
`;
// endregion: leadbay_update_lens_filter

// Map for legacy callers; prefer importing the named constant directly.
export const TOOL_DESCRIPTIONS = {
  leadbay_account_status,
  leadbay_add_note,
  leadbay_adjust_audience,
  leadbay_answer_clarification,
  leadbay_bulk_enrich_status,
  leadbay_bulk_qualify_leads,
  leadbay_clear_selection,
  leadbay_clear_user_prompt,
  leadbay_create_custom_field,
  leadbay_create_lens,
  leadbay_create_lens_draft,
  leadbay_deselect_leads,
  leadbay_discover_leads,
  leadbay_dismiss_clarification,
  leadbay_enrich_contacts,
  leadbay_enrich_titles,
  leadbay_get_clarification,
  leadbay_get_contacts,
  leadbay_get_enrichment_job_titles,
  leadbay_get_epilogue_responses,
  leadbay_get_lead_activities,
  leadbay_get_lead_notes,
  leadbay_get_lead_profile,
  leadbay_get_lens_filter,
  leadbay_get_lens_scoring,
  leadbay_get_prospecting_actions,
  leadbay_get_quota,
  leadbay_get_selection_ids,
  leadbay_get_taste_profile,
  leadbay_get_user_prompt,
  leadbay_get_web_fetch,
  leadbay_import_and_qualify,
  leadbay_import_leads,
  leadbay_import_status,
  leadbay_launch_bulk_enrichment,
  leadbay_list_lenses,
  leadbay_list_mappable_fields,
  leadbay_list_sectors,
  leadbay_login,
  leadbay_pick_clarification,
  leadbay_prepare_outreach,
  leadbay_preview_bulk_enrichment,
  leadbay_promote_lens,
  leadbay_pull_leads,
  leadbay_qualify_lead,
  leadbay_qualify_status,
  leadbay_recall_ordered_titles,
  leadbay_refine_prompt,
  leadbay_remove_epilogue,
  leadbay_report_outreach,
  leadbay_research_company,
  leadbay_research_lead,
  leadbay_resolve_import_rows,
  leadbay_select_leads,
  leadbay_set_active_lens,
  leadbay_set_epilogue_status,
  leadbay_set_user_prompt,
  leadbay_update_lens,
  leadbay_update_lens_filter,
} as const;

export type ToolDescriptionName = keyof typeof TOOL_DESCRIPTIONS;
