// AUTO-GENERATED by @leadbay/promptforge — do not edit directly.
// Regenerate via: pnpm prompts:build
// Source-of-truth: packages/promptforge/{prompts,tool-descriptions}/*.md.tmpl

// Prompt bodies, alphabetized by frontmatter.name.

// region: leadbay_daily_check_in
export const leadbay_daily_check_in: string = `
Run the Leadbay daily check-in for me. Treat this prompt the same way for any equivalent ask: "get me leadbay leads", "best leads to prospect today", "what should I work on", "show me my batch".

# PHASE 1 — STATE
Call \`leadbay_account_status\` to see what quota I have left and which lens is active. Note the remaining \`ai_rescore_remaining\` and \`web_fetch_remaining\` budgets — Phase 4 enrichment depends on them.

# PHASE 2 — FRESH BATCH
Call \`leadbay_pull_leads\` to get today's fresh batch.

# PHASE 3 — TRIAGE (top 10, motivational framing)

Pick the top **10** leads — prefer leads with a fresh \`ai_agent_lead_score\` (those have been newly AI-qualified); fall back to \`score\` only when \`ai_agent_lead_score\` is absent. For each, write ONE motivational sentence — framed as *why prospecting this lead today might be a good idea right now* (almost a coach's nudge, not a flat description). Lean on \`qualification_summary\` for the substance, but reframe — don't paste it verbatim.

If the batch returns fewer than 10 qualified leads, top it up by calling \`leadbay_bulk_qualify_leads\` with \`count\` set a bit above what you still need (some leads may get disqualified during qualification — request 1.5x the deficit, capped at 25). Then re-pull the batch and continue. (The \`leadbay_qualify_top_n\` slash-prompt wraps this same tool with a friendlier surface for users; agents should call the underlying tool directly here.)

# PHASE 4 — DEEP DIVE (every promising lead)

Call \`leadbay_research_lead\` on **every** lead from your top 10 that the user might realistically prospect today (filter out clearly weak fits if any). Don't pick just one. For each researched lead surface:
- what makes it promising (1–2 sentences citing signals from the research)
- the **recommended contacts** the research returns — name, title, why they're the right starting point

Then ASK the user (don't auto-run): "Want me to enrich the contacts on these leads to acquire their emails / phone numbers?" If the user says yes, call \`leadbay_enrich_contacts\` for the relevant lead IDs (this consumes enrichment quota — that's why we ask first).

# GATE — STOP

IRON LAW — DO NOT TAKE OUTBOUND ACTION. Do not call \`leadbay_report_outreach\`. Do not draft an outreach message into a tool argument. Outreach is the user's call after they've reviewed your research.

Render this acknowledgment VERBATIM as the last line of your message:

\`\`\`
STOP — awaiting user decision. I will not take any further action until you tell me what to do next.
\`\`\`

Do not propose a next action. Do not call any more tools. Hand control back to the user.
`;
// endregion: leadbay_daily_check_in

// region: leadbay_import_file
export const leadbay_import_file: string = `
Import the user's Leadbay file{{arg:file_paren}} and satisfy this instruction: {{arg:instruction_or_default}}.

# GOAL — what we're actually trying to do

The job is to **prepare the file so the Leadbay system ingests and matches as many rows as possible**. Every choice you make in the phases below — column mapping, domain derivation, identity resolution, custom-field creation — exists to maximize that match rate. The user shouldn't have to lose data because a header was unusual, a website was missing, or a CRM column had no obvious counterpart in Leadbay.

A job well done has TWO deliverables:
1. **Maximum-coverage column mapping**: every meaningful source column is mapped — to a standard Leadbay field where one exists, to a CONTACT_* field for person columns, to a custom field where no standard fits (including the CRM record link as a special EXTERNAL_ID custom field that's later clickable inside Leadbay), or to a Leadbay note for free-text context. Dropping data is the failure case; finding it a home is the success case.
2. **An augmented file**: the user's original file enriched with a new \`LEADBAY_ID\` column populated wherever you confidently disambiguated a match. The user keeps this as their audit trail of what got ingested and what didn't.

IRON LAW — NO FABRICATION. Every lead id, contact email, custom field id, mapping decision, and tool argument must trace to a value you read from the file the user attached or to an output from a leadbay_* tool call in this session. Do not invent values. Do not "fill in" a missing leadId with a name match. Do not synthesize a CRM id from a guess. If a value is missing, leave the field blank and say so.


# PHASE 1 — SCAN

Read the file yourself. Inspect every header, sample values from multiple rows, row count, duplicate/blank columns, and obvious dirty data. Build a column preservation plan before importing: for each meaningful column decide standard field, CONTACT_* field, Leadbay note, custom field, derived helper, or skip with a reason. Default to preserving client-provided business data; skip only blank placeholders, duplicate plumbing, raw unparsed blobs after extracting their useful values, or values that would actively harm data quality.

## GATE 1 — COLUMN PRESERVATION PLAN

Before calling any leadbay_* tool, render the COLUMN PRESERVATION PLAN byproduct in your response. Do NOT proceed to PHASE 2 until this table is in your output.

Render this block VERBATIM as your byproduct:

\`\`\`
COLUMN PRESERVATION PLAN
========================
| Source column      | Disposition                       | Reason                            |
|--------------------|-----------------------------------|-----------------------------------|
| <header from file> | standard:LEAD_NAME                | cleaned company name              |
| <header>           | standard:LEAD_WEBSITE             | domain agrees with brand          |
| <header>           | contact:CONTACT_EMAIL             | per-person mailbox                |
| <header>           | custom:HubSpot record (EXTERNAL_ID)| preserve link via url_template   |
| <header>           | note                              | meaningful per-lead context       |
| <header>           | derived:company_domain            | extracted from biz email          |
| <header>           | skip                              | blank placeholder / dup plumbing  |
========================
\`\`\`

One row per meaningful source column. If you have 30+ columns, group blank/duplicate-plumbing columns under a single "skip" row with the count.


# PHASE 2 — DERIVE (especially: company domain)

**Domain extraction is the single biggest lever for match success.** A row with a company website resolves cleanly; a row without one drops to name-based fuzzy matching, which is unreliable. Whenever a row has no \`website\`/\`domain\` column but DOES have a contact email at a real business domain, derive a \`company_domain\` (and treat it as \`LEAD_WEBSITE\` for resolution) — that one move can turn a 60% match rate into 90%.

**Domain extraction is a key factor of match success.** Build semantic helper columns BEFORE resolving identities. The Leadbay matcher leans heavily on \`LEAD_WEBSITE\`/\`company_domain\`; rows that arrive without one drop to fuzzy name matching, which is unreliable. Whenever a row lacks a website/domain column but contains a contact email at a real business domain, derive a \`company_domain\` from the email and treat it as \`LEAD_WEBSITE\` for resolution — but ONLY when that domain agrees with the company/deal/brand context (do not blindly use whatever's after the @).

Ignore consumer mailbox domains such as gmail.com, hotmail.com, outlook.com, yahoo.com, icloud.com, proton.me/protonmail.com, aol.com, live.com, msn.com, me.com, gmx.*, and similar personal email providers — these are NOT company domains. Also ignore POS/vendor/group domains that conflict with the company (e.g. a \`square.com\` email on a coffee-shop row is the POS provider, not the shop). Keep the original email for CONTACT_EMAIL.

When in doubt, sample several rows that share a candidate derived domain and confirm the company names cluster sensibly under it before committing.


# PHASE 3 — RESOLVE IDENTITIES

Decide resolver \`identity_mappings\` from the actual file semantics. Prefer: website/domain/url or **vetted derived business email domain** -> website; cleaned company/account/restaurant/establishment name -> name; CRM/system id -> crm_id; registry/SIREN/SIRET/company number -> registry_number; full address/city/postcode/country/phone/email/socials when present. For HubSpot/deal exports, clean campaign suffixes like BYOC, BYOC only, DD, Uber, trailing separators, and duplicate pipeline labels before using the value as LEAD_NAME. If a column is ambiguous, inspect row values before mapping it. Do not rely on fixed header names.

Call \`leadbay_resolve_import_rows\` with representative or all rows and your explicit \`identity_mappings\`. For large files, batch rows so responses stay readable. Use \`include_candidate_profiles=true\` for small batches or rerun it on ambiguous rows only. If a row is ambiguous and candidate profiles are missing or truncated, rerun just those rows with \`include_candidate_profiles=true\` and a larger \`candidate_profile_limit\` before deciding.

Disambiguate relentlessly. Use matched \`lead_id\` values directly. For ambiguous candidates, first make sure you have enough evidence: rerun the ambiguous rows with \`include_candidate_profiles=true\` and a larger \`candidate_profile_limit\` if profiles are truncated, and include every trustworthy source signal available (website, full address, postcode, city, phone, registry/CRM id, source URL path, neighborhood/location words).

Compare addresses intelligently as a human would: recognize ordinary formatting, abbreviation, spelling, punctuation, casing, direction, ordinal, and suite/unit differences without reducing the decision to rigid rules.

Write LEADBAY_ID when candidate facts uniquely agree with strong source evidence: exact registry/CRM id, exact phone, exact canonical website/domain with only one candidate, or name plus clear same-place address match with postcode/city and no conflict. If several candidates share the same website/domain, treat it as a chain/multi-location problem and use street address, postcode, city/neighborhood, phone, source URL path/location slug, and location words in the source name to pick the specific place when exactly one candidate matches.


# WHAT GOOD LOOKS LIKE — the disambiguation bar

A "good" run produces an **augmented file** (input file + a new LEADBAY_ID column) where every row that COULD be confidently matched IS matched, and every row that couldn't is honestly left blank with the reason. Concretely:

- Write LEADBAY_ID when candidate facts uniquely agree with strong source evidence: exact registry/CRM id, exact phone, exact canonical website/domain with only one candidate, or name plus clear same-place address match with postcode/city and no conflict.
- For chain/multi-location problems (several candidates share the same website/domain), use street address, postcode, city/neighborhood, phone, source URL path/location slug, and location words in the source name to pick the specific place when exactly one candidate matches.
- **Never** pick LEADBAY_ID from score alone, name-only, fuzzy-name-only, generic directory websites, root-domain-only, brand-only, postcode-only, or city-only evidence.
- Leave LEADBAY_ID blank only after those checks still leave real ambiguity, and record why in the DECISION LOG.

A row left blank with a clear reason is a SUCCESS, not a failure — it gives the user an honest audit trail. Fabricating an ID is a critical failure.

## GATE 3 — DECISION LOG

Before writing LEADBAY_ID for any ambiguous row, render the DECISION LOG byproduct in your response. One line per row that was not a deterministic match.

Append one line per ambiguous-or-resolved row to the DECISION LOG block:

\`\`\`
DECISION LOG
============
row <N>: LEADBAY_ID=<id|blank>  evidence=<which signals agreed>  rejected=<why other candidates were not chosen>
row <N>: LEADBAY_ID=<id|blank>  evidence=<...>                   rejected=<...>
============
\`\`\`

For rows where no resolution was possible, write \`LEADBAY_ID=blank evidence=insufficient\` and explain in \`rejected=\` why the available signals were not enough.


# PHASE 4 — PRESERVE & COMMIT

Build a clean records array for import from the preservation plan. Preserve user-requested and semantically meaningful business fields, add LEADBAY_ID where resolved, normalize obvious scalar fields, and split JSON/list blobs into useful scalar columns when they contain real business data. For meaningful columns with no standard Leadbay field, call \`leadbay_list_mappable_fields\` and create/reuse custom fields rather than dropping the data. Drop blank-header columns and placeholder values like \`couldn't find\`, \`yes\`, empty arrays, and raw JSON after useful values have been extracted. Do not preserve scraper plumbing, duplicate blank columns, or long reasoning text, but do preserve meaningful client notes, data-quality warnings that affect outreach, source record links, and evidence URLs when they help the user's workflow.

Treat contact exports and embedded owner/contact data as lead+contact imports. Map the parent company identity columns (LEADBAY_ID/LEAD_WEBSITE/LEAD_NAME/CRM_ID/SIREN) and also map person columns to CONTACT_FIRST_NAME, CONTACT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE_NUMBER, CONTACT_TITLE, CONTACT_LINKEDIN. If a restaurant/company row contains structured owners, decision makers, or contact lists, expand those people into additional import rows that repeat the parent lead identity and contain one CONTACT_* person per row. Multiple rows may share the same LEADBAY_ID/company; import each row as a contact for that lead.

**Preserve the source CRM record as a clickable link.** Source CRM URLs/ids — HubSpot, Salesforce, Pipedrive, Close, Attio, or anything similar — are high-value: they let the user click straight from a Leadbay lead back to the original record in their CRM. Don't drop them.

Workflow:
1. Call \`leadbay_list_mappable_fields\` first; if a suitable EXTERNAL_ID-style field already exists for the source CRM, reuse it.
2. If no suitable field exists, call \`leadbay_create_custom_field\` with \`kind=EXTERNAL_ID\` and a \`config.url_template\` for the specific CRM. Pass the stable object id (not the URL) as the value.

Per-CRM templates — pass the CRM's stable object id as \`{value}\`:
- **HubSpot**: \`https://app.hubspot.com/contacts/<portal-id>/record/0-1/{value}\` (companies) or \`.../record/0-2/{value}\` (contacts) or \`.../record/0-3/{value}\` (deals)
- **Salesforce**: \`https://<your-instance>.lightning.force.com/lightning/r/Account/{value}/view\` (Accounts) or \`.../Lead/{value}/view\`, \`.../Contact/{value}/view\`, \`.../Opportunity/{value}/view\`
- **Pipedrive**: \`https://<your-domain>.pipedrive.com/organization/{value}\` or \`.../person/{value}\` or \`.../deal/{value}\`
- **Close**: \`https://app.close.com/lead/{value}/\`
- **Attio**: \`https://app.attio.com/<workspace-slug>/company/{value}\`
- **Other CRMs**: ask the user for the URL template; if they don't know, fall back to a TEXT custom field for the full URL.

Preserve raw source identifiers (e.g. \`hubspot_id\`, \`salesforce_account_id\`, \`associated_deal\`, \`pipedrive_org_id\`) in custom fields when they aren't already represented by a better standard/custom field. If only a full URL exists and no stable id/template can be recovered, create/use a TEXT custom field for the URL.

Leadbay has CONTACT_PHONE_NUMBER but no standard LEAD_PHONE in this tool surface; preserve establishment/company phone only via an intentional custom field.


Preserve notes intentionally. If the file contains meaningful per-lead notes/context that should live as Leadbay notes, keep them aside during import and, after the import returns lead IDs, call \`leadbay_add_note\` for the relevant imported/resolved leads when that tool is available. For dry runs, report which notes would be written. If lead notes are not available and the user asked to preserve the text, create/reuse an import-notes custom field instead of dropping it.

Build the final mappings yourself. Start from \`leadbay_resolve_import_rows.mappings_for_import\`, then map semantically: LEADBAY_ID, LEAD_WEBSITE, LEAD_NAME, CRM_ID, SIREN, LEAD_LOCATION*, LEAD_SECTOR, LEAD_SIZE, contact fields, and useful \`CUSTOM.<id>\` fields. Call \`leadbay_list_mappable_fields\` before using custom fields.

# PHASE 5 — QUALIFY (optional) + REPORT

Prefer \`leadbay_import_and_qualify\` when the user asks to qualify/research after import; otherwise use \`leadbay_import_leads\`. For large files or short client timeouts, pass \`wait_for_completion=false\` and poll \`leadbay_import_status\`. After import, qualify only lead IDs returned by the import; late website matches may appear later via \`import_status\`.

**Deliver the augmented file back to the user**: the original file plus a new \`LEADBAY_ID\` column populated from the resolution step. This is the second deliverable of a job well done.

## GATE 5 — FINAL REPORT

Before ending the session, render the FINAL REPORT byproduct in your response.

Render the FINAL REPORT block VERBATIM as your byproduct:

\`\`\`
FINAL REPORT
============
rows read:                 <n>
rows skipped (blank/dup):  <n>
deterministic matches:     <n>
ambiguous left unresolved: <n>
contacts imported:         <n>
notes written or staged:   <n>
custom fields created:     <n>
custom fields reused:      <n>
import IDs / handle IDs:   <list>
leads imported now:        <list-or-count>
needs later polling:       <yes/no, via leadbay_import_status>
============
\`\`\`

If any field is N/A for this run, render the row with \`n/a\` instead of dropping it.
`;
// endregion: leadbay_import_file

// region: leadbay_log_outreach
export const leadbay_log_outreach: string = `
IRON LAW — VERIFICATION REQUIRED. Before calling leadbay_report_outreach, you MUST collect one of: a gmail message id (verification.source = 'gmail_message_id'), a calendar event id (verification.source = 'calendar_event_id'), or a literal one-sentence user confirmation (verification.source = 'user_confirmed', verification.ref = the user's exact words). Skipping or fabricating verification poisons the human team's pipeline.


Log this outreach on Leadbay lead {{arg:lead_id}}:
Summary: {{arg:summary}}

# PHASE 1 — COLLECT VERIFICATION (ask the user EXACTLY once)

Before calling \`leadbay_report_outreach\`, ask me ONCE which of these applies:

- I sent an **email** → ask for the Gmail message id (\`verification.source = 'gmail_message_id'\`, \`verification.ref = <the id>\`).
- I booked a **meeting** → ask for the calendar event id (\`verification.source = 'calendar_event_id'\`, \`verification.ref = <the id>\`).
- **Other** → ask me for a literal one-sentence confirmation that the outreach happened (\`verification.source = 'user_confirmed'\`, \`verification.ref = my exact words\`).

# PHASE 2 — RECORD

After I answer, call \`leadbay_report_outreach({lead_id: '{{arg:lead_id}}', note: <summary>, verification: {source, ref}})\`. Optionally pass \`dry_run:true\` first to confirm exactly what would be sent — recommended if I described the outreach but you're not 100% sure how to phrase the note.

# PHASE 3 — CONFIRM
Tell me the outreach was logged, name the verification.source used, and surface the response's \`outreach_id\` if present so I can refer back to it.
`;
// endregion: leadbay_log_outreach

// region: leadbay_qualify_top_n
export const leadbay_qualify_top_n: string = `
Qualify the top {{arg:count_or_default}} un-qualified leads in the active Leadbay lens.

# PHASE 1 — LAUNCH
Call \`leadbay_bulk_qualify_leads\` with \`count={{arg:count_or_default}}\`.

# PHASE 2 — POLL
While it polls, expect notifications / progress events showing per-lead transitions. Surface meaningful ones (e.g. "lead X just finished") to me as they arrive.

# PHASE 3 — SUMMARIZE

When \`bulk_qualify_leads\` returns, summarize:
- How many qualified (name the count)
- How many are still running (name them, by lead_id + lead name if available, so I can poll again later)
- The 3 highest-\`ai_agent_lead_score\` leads from THIS batch, with their \`qualification_summary\` (one sentence each)

# PHASE 4 — RECOMMEND
Recommend the single most-promising lead from this batch and offer to research it deeply with \`leadbay_research_lead\`. Do not actually call \`research_lead\` yet — wait for my go.
`;
// endregion: leadbay_qualify_top_n

// region: leadbay_refine_audience
export const leadbay_refine_audience: string = `
Refine the Leadbay audience prompt to: {{arg:instruction}}

# PHASE 1 — REFINE
Call \`leadbay_refine_prompt\` with \`prompt=<the instruction above>\`.

# PHASE 2 — CLARIFICATION ROUND-TRIP (if needed)

IRON LAW — DO NOT ANSWER CLARIFICATIONS ON THE USER'S BEHALF. If the response includes a \`clarification\` block, surface the question and options to me VERBATIM and wait. Do NOT call \`leadbay_answer_clarification\`. I want to choose.

# PHASE 3 — APPLIED OR NOT
If the response status is \`applied\`, tell me Leadbay is regenerating intelligence and recommend I check back in a few minutes via \`leadbay_account_status\` (\`computing_intelligence\` flips to false when ready). If the status is anything else, name it explicitly.
`;
// endregion: leadbay_refine_audience

// region: leadbay_research_a_domain
export const leadbay_research_a_domain: string = `
IRON LAW — NO FABRICATION. Every lead id, contact email, custom field id, mapping decision, and tool argument must trace to a value you read from the file the user attached or to an output from a leadbay_* tool call in this session. Do not invent values. Do not "fill in" a missing leadId with a name match. Do not synthesize a CRM id from a guess. If a value is missing, leave the field blank and say so.


Research the company with domain '{{arg:domain}}' for me using Leadbay.

# PHASE 1 — IMPORT + QUALIFY
Call \`leadbay_import_and_qualify\` with \`domains=[{domain:'{{arg:domain}}'}]\`. This imports the lead AND runs AI qualification in one call. If the response indicates \`quota_blocked\` or \`still_running\`, say so explicitly.

# PHASE 2 — DEEP DIVE
When the import resolves, call \`leadbay_research_lead\` on the new leadId.

# PHASE 3 — SUMMARY
Summarize:
- Who is this company (1 sentence)
- Their fit (cite specific \`qualification_answers\` from the qualification response)
- What signals stand out (cite specific research findings)
- Which contact would I email first (name, role, source)

Be honest about uncertainty: if any field above is missing from tool responses, say "not surfaced by qualification" rather than guessing.
`;
// endregion: leadbay_research_a_domain

// Prompt metadata (descriptions + arguments) for MCP listings.
export const PROMPT_META = {
  leadbay_daily_check_in: {"name":"leadbay_daily_check_in","short_description":"Run the canonical daily check-in: see account state, pull a fresh batch,\ntriage the top 10, deep-dive on every promising one, and offer contact\nenrichment. The user's typical morning workflow. Trigger when the user\nasks for \"leadbay leads\", \"best leads to prospect today\", \"what should\nI work on\", or anything resembling \"show me the day's batch\".\n","arguments":[],"expected_calls":["leadbay_account_status","leadbay_pull_leads","leadbay_research_lead","leadbay_bulk_qualify_leads","leadbay_enrich_contacts"],"failure_modes":["Calls leadbay_report_outreach without explicit user authorization","Surfaces fewer than 10 leads when more are available, or fails to top up via leadbay_qualify_top_n when the batch is short","Writes flat one-line summaries instead of motivational \"why prospect this today\" framing","Skips deep research on promising leads (Phase 4) — the agent must call leadbay_research_lead on each, not just one","Triggers contact enrichment without asking the user first (it consumes quota)","Skips the STOP byproduct and proposes next actions on its own"]},
  leadbay_import_file: {"name":"leadbay_import_file","short_description":"Import a user-supplied CSV/file into Leadbay through five phases with\nevidence gates — scan, derive, resolve identities, preserve & commit,\nthen optionally qualify and report. The job is to maximize how many\nrows the Leadbay system actually ingests and matches.\n","arguments":[{"name":"file","description":"Path or user-visible name of the CSV/file to import. If omitted, use the file the user attached or referenced.","required":false},{"name":"instruction","description":"Additional user goal, e.g. \"then qualify the leads\", \"preserve owner phone as a custom field\", or \"only import restaurants in Manhattan\".","required":false}],"expected_calls":["leadbay_resolve_import_rows","leadbay_list_mappable_fields","leadbay_create_custom_field","leadbay_import_leads","leadbay_import_and_qualify","leadbay_add_note","leadbay_import_status"],"failure_modes":["Picks LEADBAY_ID from score alone, name-only, fuzzy-name-only, root-domain-only, brand-only, postcode-only, or city-only evidence","Drops meaningful business notes or CRM record links instead of preserving them as custom fields or lead notes","Treats a consumer mailbox domain (gmail.com, hotmail.com, ...) as the company domain","Skips deriving company_domain from a business email when no website column exists (this kills match rate)","Skips the COLUMN PRESERVATION PLAN byproduct before importing","Skips the DECISION LOG byproduct before writing LEADBAY_ID","Returns the imported records WITHOUT writing LEADBAY_ID values back into the user's file (leaves the user no audit trail of what matched)","Fabricates leadIds, contact emails, or mapping IDs not present in the file or a tool response"]},
  leadbay_log_outreach: {"name":"leadbay_log_outreach","short_description":"Log outreach (an email I sent, a call I made, a meeting I had) on a\nspecific lead. Captures verification so the SDR pipeline trusts the entry.\n","arguments":[{"name":"lead_id","description":"The lead UUID. Get it from leadbay_pull_leads or leadbay_research_lead.","required":true},{"name":"summary","description":"1-2 sentences describing what I did (e.g. 'Sent intro email to CTO citing recent Hornsea contract').","required":true}],"expected_calls":["leadbay_report_outreach"],"failure_modes":["Calls leadbay_report_outreach without first collecting a verification source","Fabricates a gmail_message_id or calendar_event_id (the human team treats verification as canonical)","Records outreach to a different lead_id than the one the user supplied","Skips the dry_run step when the user is unsure what would be sent"]},
  leadbay_qualify_top_n: {"name":"leadbay_qualify_top_n","short_description":"Bulk-qualify the top N un-qualified leads in the active lens. Uses\nleadbay_bulk_qualify_leads with a sensible default budget.\n","arguments":[{"name":"count","description":"How many leads to qualify (default 10, max 25). Higher counts may take 5+ minutes.","required":false}],"expected_calls":["leadbay_bulk_qualify_leads","leadbay_research_lead"],"failure_modes":["Picks a count larger than the user asked for (or larger than the max 25)","Glosses over still-running leads in the summary instead of naming them","Recommends a lead from the existing qualified pool instead of one from this batch's actual results"]},
  leadbay_refine_audience: {"name":"leadbay_refine_audience","short_description":"Refine the kind of leads Leadbay surfaces beyond firmographics, with a\nfree-text instruction. Handles the clarification round-trip if the new\nprompt is ambiguous.\n","arguments":[{"name":"instruction","description":"The refinement (e.g. 'focus on hospitals running their own IT'). Set to plain English.","required":true}],"expected_calls":["leadbay_refine_prompt","leadbay_account_status"],"failure_modes":["Calls leadbay_answer_clarification on the user's behalf instead of surfacing the clarification verbatim","Glosses over the clarification options instead of presenting them as offered","Promises immediate effect when status='applied' actually triggers an async intelligence recompute"]},
  leadbay_research_a_domain: {"name":"leadbay_research_a_domain","short_description":"Import a company by domain and run deep qualification + research in one\npass. Use when a colleague mentions a name and you want everything Leadbay\nknows about it.\n","arguments":[{"name":"domain","description":"The company's primary domain (e.g. 'acme.com'). Protocol/path are stripped.","required":true}],"expected_calls":["leadbay_import_and_qualify","leadbay_research_lead"],"failure_modes":["Fabricates qualification answers not present in any tool response","Reports certainty about fit when qualification didn't actually run (e.g. quota_blocked)","Skips the research step after import completes"]},
} as const;

export type PromptName = keyof typeof PROMPT_META;
