import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import type { AssembledArtifact, AssembleResult } from "./assembler.js";

const HEADER = `// AUTO-GENERATED by @leadbay/promptforge — do not edit directly.
// Regenerate via: pnpm prompts:build
// Source-of-truth: packages/promptforge/{prompts,tool-descriptions}/*.md.tmpl

`;

function escapeBacktick(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function emitConst(artifact: AssembledArtifact): string {
  const { name } = artifact.frontmatter;
  const escaped = escapeBacktick(artifact.body);
  return `// region: ${name}
export const ${name}: string = \`${escaped}\`;
// endregion: ${name}
`;
}

function emitPromptMeta(artifact: AssembledArtifact): string {
  const fm = artifact.frontmatter;
  const args = (fm.arguments ?? []).map((a) => ({
    name: a.name,
    description: a.description,
    required: a.required ?? false,
  }));
  return JSON.stringify({
    name: fm.name,
    short_description: fm.short_description,
    arguments: args,
    expected_calls: fm.expected_calls ?? [],
    failure_modes: fm.failure_modes ?? [],
  });
}

export interface EmitOptions {
  promptsOutPath: string;       // e.g. packages/mcp/src/prompts.generated.ts
  toolDescriptionsOutPath: string; // e.g. packages/core/src/tool-descriptions.generated.ts
}

export interface EmitOutput {
  promptsModule: string;
  toolDescriptionsModule: string;
}

export function emit(result: AssembleResult): EmitOutput {
  // Prompts module
  const promptParts: string[] = [HEADER];
  promptParts.push("// Prompt bodies, alphabetized by frontmatter.name.\n\n");
  for (const p of result.prompts) {
    promptParts.push(emitConst(p));
    promptParts.push("\n");
  }
  promptParts.push("// Prompt metadata (descriptions + arguments) for MCP listings.\n");
  promptParts.push("export const PROMPT_META = {\n");
  for (const p of result.prompts) {
    promptParts.push(`  ${p.frontmatter.name}: ${emitPromptMeta(p)},\n`);
  }
  promptParts.push("} as const;\n\n");
  promptParts.push("export type PromptName = keyof typeof PROMPT_META;\n");

  // Tool descriptions module
  const toolParts: string[] = [HEADER];
  toolParts.push("// Tool descriptions, alphabetized by frontmatter.name.\n\n");
  for (const t of result.toolDescriptions) {
    toolParts.push(emitConst(t));
    toolParts.push("\n");
  }
  toolParts.push("// Map for legacy callers; prefer importing the named constant directly.\n");
  toolParts.push("export const TOOL_DESCRIPTIONS = {\n");
  for (const t of result.toolDescriptions) {
    toolParts.push(`  ${t.frontmatter.name},\n`);
  }
  toolParts.push("} as const;\n\n");
  toolParts.push("export type ToolDescriptionName = keyof typeof TOOL_DESCRIPTIONS;\n");

  return {
    promptsModule: promptParts.join(""),
    toolDescriptionsModule: toolParts.join(""),
  };
}

export function writeIfDifferent(path: string, content: string): { changed: boolean } {
  mkdirSync(dirname(path), { recursive: true });
  if (existsSync(path)) {
    const current = readFileSync(path, "utf8");
    if (current === content) return { changed: false };
  }
  writeFileSync(path, content, "utf8");
  return { changed: true };
}

export function diff(path: string, content: string): { matches: boolean; current: string | null } {
  if (!existsSync(path)) return { matches: false, current: null };
  const current = readFileSync(path, "utf8");
  return { matches: current === content, current };
}
