import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import type { AssembledArtifact, AssembleResult } from "./assembler.js";
import type { PromptArgument } from "./frontmatter.js";

const HEADER = `// AUTO-GENERATED by @leadbay/promptforge — do not edit directly.
// Regenerate via: pnpm prompts:build
// Source-of-truth: packages/promptforge/{prompts,tool-descriptions}/*.md.tmpl

`;

function escapeBacktick(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function emitConst(artifact: AssembledArtifact): string {
  const { name } = artifact.frontmatter;
  const escaped = escapeBacktick(artifact.body);
  return `// region: ${name}
export const ${name}: string = \`${escaped}\`;
// endregion: ${name}
`;
}

function emitPromptMeta(artifact: AssembledArtifact): string {
  const fm = artifact.frontmatter;
  const args = (fm.arguments ?? []).map((a) => ({
    name: a.name,
    description: a.description,
    required: a.required ?? false,
  }));
  return JSON.stringify({
    name: fm.name,
    short_description: fm.short_description,
    arguments: args,
    expected_calls: fm.expected_calls ?? [],
    failure_modes: fm.failure_modes ?? [],
  });
}

export interface EmitOptions {
  promptsOutPath: string;       // e.g. packages/mcp/src/prompts.generated.ts
  toolDescriptionsOutPath: string; // e.g. packages/core/src/tool-descriptions.generated.ts
}

export interface EmitOutput {
  promptsModule: string;
  toolDescriptionsModule: string;
}

function describeArguments(args: PromptArgument[] | undefined): string {
  if (!args || args.length === 0) return "";
  const required = args.filter((a) => a.required).map((a) => a.name);
  const optional = args.filter((a) => !a.required).map((a) => a.name);
  const parts: string[] = [];
  if (required.length > 0) parts.push(`required args: ${required.join(", ")}`);
  if (optional.length > 0) parts.push(`optional args: ${optional.join(", ")}`);
  return ` (${parts.join("; ")})`;
}

function singleLineShortDescription(desc: string): string {
  // short_description in frontmatter is typically a YAML block scalar with
  // hard wraps. Collapse to a single line for the instructions string.
  return desc.replace(/\s+/g, " ").trim();
}

/**
 * Build the prompt-catalog header + per-prompt bullets the MCP server
 * splices into its `initialize` `instructions` payload.
 *
 * Clients that don't render prompts in their UI (Cowork is the prototypical
 * case) get this catalog as system prompt context so the agent knows the
 * prompts exist and can invoke them directly via `prompts/get`. Clients
 * that DO render prompts as slash commands (Claude Desktop, Cursor) read
 * the same string but it's redundant for them — that's fine; it's cheap.
 *
 * Bullets are exported as a record (name → line) so the server can filter
 * by exposed-tool gating. The iter-12 invariant — the server's instructions
 * never name a tool that isn't actually registered — requires this:
 * `leadbay_qualify_top_n`'s short_description literally references
 * `leadbay_bulk_qualify_leads`, so its bullet must be suppressed when the
 * underlying tool is gated off. The server inspects each bullet for
 * `leadbay_*` references and drops bullets whose referenced tools aren't
 * exposed.
 */
const CATALOG_HEADER =
  "This server exposes the following workflow prompts via `prompts/list` " +
  "and `prompts/get`. Some MCP clients render them as slash commands; if " +
  "your client does not, you (the agent) should invoke them directly via " +
  "`prompts/get` when the user's request matches one of the triggers " +
  "described below.";

function emitCatalogBullet(artifact: AssembledArtifact): string {
  const argsHint = describeArguments(artifact.frontmatter.arguments);
  const desc = singleLineShortDescription(artifact.frontmatter.short_description);
  return `- \`${artifact.frontmatter.name}\`${argsHint}: ${desc}`;
}

function emitPromptCatalogInstructions(prompts: AssembledArtifact[]): string {
  const bullets = prompts.map(emitCatalogBullet);
  return [CATALOG_HEADER, "", ...bullets].join("\n");
}

export function emit(result: AssembleResult): EmitOutput {
  // Prompts module
  const promptParts: string[] = [HEADER];
  promptParts.push("// Prompt bodies, alphabetized by frontmatter.name.\n\n");
  for (const p of result.prompts) {
    promptParts.push(emitConst(p));
    promptParts.push("\n");
  }
  promptParts.push("// Prompt metadata (descriptions + arguments) for MCP listings.\n");
  promptParts.push("export const PROMPT_META = {\n");
  for (const p of result.prompts) {
    promptParts.push(`  ${p.frontmatter.name}: ${emitPromptMeta(p)},\n`);
  }
  promptParts.push("} as const;\n\n");
  promptParts.push("export type PromptName = keyof typeof PROMPT_META;\n\n");

  // Catalog block for the MCP server's `initialize` instructions payload.
  //
  // PROMPT_CATALOG_HEADER is the static intro string.
  // PROMPT_CATALOG_BULLETS maps prompt name → its one-line catalog bullet so
  //   the server can filter by exposed-tool gating (iter-12 invariant).
  // PROMPT_CATALOG_INSTRUCTIONS is the pre-joined header + all bullets, kept
  //   as a convenience for callers that want the full catalog (tests; clients
  //   that always expose every tool).
  promptParts.push(
    "// Prompt catalog block the MCP server splices into its initialize instructions.\n",
  );
  promptParts.push(
    `export const PROMPT_CATALOG_HEADER: string = \`${escapeBacktick(CATALOG_HEADER)}\`;\n\n`,
  );
  promptParts.push("export const PROMPT_CATALOG_BULLETS = {\n");
  for (const p of result.prompts) {
    const bullet = emitCatalogBullet(p);
    promptParts.push(`  ${p.frontmatter.name}: \`${escapeBacktick(bullet)}\`,\n`);
  }
  promptParts.push("} as const;\n\n");
  const catalog = emitPromptCatalogInstructions(result.prompts);
  promptParts.push(
    `export const PROMPT_CATALOG_INSTRUCTIONS: string = \`${escapeBacktick(catalog)}\`;\n`,
  );

  // Tool descriptions module
  const toolParts: string[] = [HEADER];
  toolParts.push("// Tool descriptions, alphabetized by frontmatter.name.\n\n");
  for (const t of result.toolDescriptions) {
    toolParts.push(emitConst(t));
    toolParts.push("\n");
  }
  toolParts.push("// Map for legacy callers; prefer importing the named constant directly.\n");
  toolParts.push("export const TOOL_DESCRIPTIONS = {\n");
  for (const t of result.toolDescriptions) {
    toolParts.push(`  ${t.frontmatter.name},\n`);
  }
  toolParts.push("} as const;\n\n");
  toolParts.push("export type ToolDescriptionName = keyof typeof TOOL_DESCRIPTIONS;\n");

  return {
    promptsModule: promptParts.join(""),
    toolDescriptionsModule: toolParts.join(""),
  };
}

export function writeIfDifferent(path: string, content: string): { changed: boolean } {
  mkdirSync(dirname(path), { recursive: true });
  if (existsSync(path)) {
    const current = readFileSync(path, "utf8");
    if (current === content) return { changed: false };
  }
  writeFileSync(path, content, "utf8");
  return { changed: true };
}

export function diff(path: string, content: string): { matches: boolean; current: string | null } {
  if (!existsSync(path)) return { matches: false, current: null };
  const current = readFileSync(path, "utf8");
  return { matches: current === content, current };
}
