import { writeFileSync, readFileSync, existsSync, mkdirSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import type { AssembledArtifact, AssembleResult } from "./assembler.js";
import type { PromptArgument } from "./frontmatter.js";
import { hasCommerceMarkers, renderCommerce } from "./commerce.js";

const HEADER = `// AUTO-GENERATED by @leadbay/promptforge — do not edit directly.
// Regenerate via: pnpm prompts:build
// Source-of-truth: packages/promptforge/{prompts,tool-descriptions}/*.md.tmpl

`;

function escapeBacktick(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function emitConst(artifact: AssembledArtifact): string {
  const { name } = artifact.frontmatter;
  const escaped = escapeBacktick(artifact.body);
  return `// region: ${name}
export const ${name}: string = \`${escaped}\`;
// endregion: ${name}
`;
}

function emitPromptMeta(artifact: AssembledArtifact): string {
  const fm = artifact.frontmatter;
  const args = (fm.arguments ?? []).map((a) => ({
    name: a.name,
    description: a.description,
    required: a.required ?? false,
  }));
  return JSON.stringify({
    name: fm.name,
    short_description: fm.short_description,
    arguments: args,
    expected_calls: fm.expected_calls ?? [],
    failure_modes: fm.failure_modes ?? [],
  });
}

export interface EmitOptions {
  promptsOutPath: string;       // e.g. packages/mcp/src/prompts.generated.ts
  toolDescriptionsOutPath: string; // e.g. packages/core/src/tool-descriptions.generated.ts
}

export interface EmitOutput {
  promptsModule: string;
  toolDescriptionsModule: string;
}

function describeArguments(args: PromptArgument[] | undefined): string {
  if (!args || args.length === 0) return "";
  const required = args.filter((a) => a.required).map((a) => a.name);
  const optional = args.filter((a) => !a.required).map((a) => a.name);
  const parts: string[] = [];
  if (required.length > 0) parts.push(`required args: ${required.join(", ")}`);
  if (optional.length > 0) parts.push(`optional args: ${optional.join(", ")}`);
  return ` (${parts.join("; ")})`;
}

function singleLineShortDescription(desc: string): string {
  // short_description in frontmatter is typically a YAML block scalar with
  // hard wraps. Collapse to a single line for the instructions string.
  return desc.replace(/\s+/g, " ").trim();
}

/**
 * Build the prompt-catalog header + per-prompt bullets the MCP server
 * splices into its `initialize` `instructions` payload.
 *
 * Clients that don't render prompts in their UI (Cowork is the prototypical
 * case) get this catalog as system prompt context so the agent knows the
 * prompts exist and can invoke them directly via `prompts/get`. Clients
 * that DO render prompts as slash commands (Claude Desktop, Cursor) read
 * the same string but it's redundant for them — that's fine; it's cheap.
 *
 * Bullets are exported as a record (name → line) so the server can filter
 * by exposed-tool gating. The iter-12 invariant — the server's instructions
 * never name a tool that isn't actually registered — requires this:
 * `leadbay_qualify_top_n`'s short_description literally references
 * `leadbay_bulk_qualify_leads`, so its bullet must be suppressed when the
 * underlying tool is gated off. The server inspects each bullet for
 * `leadbay_*` references and drops bullets whose referenced tools aren't
 * exposed.
 */
const CATALOG_HEADER =
  "This server exposes the following workflow prompts via `prompts/list` " +
  "and `prompts/get`. Some MCP clients render them as slash commands; if " +
  "your client does not, you (the agent) should invoke them directly via " +
  "`prompts/get` when the user's request matches one of the triggers " +
  "described below.";

function emitCatalogBullet(artifact: AssembledArtifact): string {
  const argsHint = describeArguments(artifact.frontmatter.arguments);
  const desc = singleLineShortDescription(artifact.frontmatter.short_description);
  return `- \`${artifact.frontmatter.name}\`${argsHint}: ${desc}`;
}

function emitPromptCatalogInstructions(prompts: AssembledArtifact[]): string {
  const bullets = prompts.map(emitCatalogBullet);
  return [CATALOG_HEADER, "", ...bullets].join("\n");
}

export function emit(result: AssembleResult): EmitOutput {
  // Prompts module
  const promptParts: string[] = [HEADER];
  promptParts.push("// Prompt bodies, alphabetized by frontmatter.name.\n\n");
  for (const p of result.prompts) {
    promptParts.push(emitConst(p));
    promptParts.push("\n");
  }
  promptParts.push("// Prompt metadata (descriptions + arguments) for MCP listings.\n");
  promptParts.push("export const PROMPT_META = {\n");
  for (const p of result.prompts) {
    promptParts.push(`  ${p.frontmatter.name}: ${emitPromptMeta(p)},\n`);
  }
  promptParts.push("} as const;\n\n");
  promptParts.push("export type PromptName = keyof typeof PROMPT_META;\n\n");

  // Catalog block for the MCP server's `initialize` instructions payload.
  //
  // PROMPT_CATALOG_HEADER is the static intro string.
  // PROMPT_CATALOG_BULLETS maps prompt name → its one-line catalog bullet so
  //   the server can filter by exposed-tool gating (iter-12 invariant).
  // PROMPT_CATALOG_INSTRUCTIONS is the pre-joined header + all bullets, kept
  //   as a convenience for callers that want the full catalog (tests; clients
  //   that always expose every tool).
  promptParts.push(
    "// Prompt catalog block the MCP server splices into its initialize instructions.\n",
  );
  promptParts.push(
    `export const PROMPT_CATALOG_HEADER: string = \`${escapeBacktick(CATALOG_HEADER)}\`;\n\n`,
  );
  promptParts.push("export const PROMPT_CATALOG_BULLETS = {\n");
  for (const p of result.prompts) {
    const bullet = emitCatalogBullet(p);
    promptParts.push(`  ${p.frontmatter.name}: \`${escapeBacktick(bullet)}\`,\n`);
  }
  promptParts.push("} as const;\n\n");
  const catalog = emitPromptCatalogInstructions(result.prompts);
  promptParts.push(
    `export const PROMPT_CATALOG_INSTRUCTIONS: string = \`${escapeBacktick(catalog)}\`;\n`,
  );

  // Tool descriptions module
  const toolParts: string[] = [HEADER];
  toolParts.push("// Tool descriptions, alphabetized by frontmatter.name.\n\n");
  for (const t of result.toolDescriptions) {
    toolParts.push(emitConst(t));
    toolParts.push("\n");
  }
  toolParts.push("// Map for legacy callers; prefer importing the named constant directly.\n");
  toolParts.push("export const TOOL_DESCRIPTIONS = {\n");
  for (const t of result.toolDescriptions) {
    toolParts.push(`  ${t.frontmatter.name},\n`);
  }
  toolParts.push("} as const;\n\n");
  toolParts.push("export type ToolDescriptionName = keyof typeof TOOL_DESCRIPTIONS;\n\n");

  // Same descriptions with the {{commerce}} blocks deleted — nothing reworded.
  // The MCP server swaps these in on a host that forbids promoting a purchase.
  // Tools absent from the map carry no commerce prose and are used as-is.
  toolParts.push(
    "// Descriptions with the {{commerce}} blocks deleted (no rewording). The MCP\n" +
      "// server swaps these in when commerce is gated off; tools absent from this\n" +
      "// map read identically on both surfaces.\n",
  );
  toolParts.push("export const NO_COMMERCE_TOOL_DESCRIPTIONS: Record<string, string> = {\n");
  for (const t of result.toolDescriptions) {
    if (!t.noCommerceBody) continue;
    toolParts.push(`  ${t.frontmatter.name}: \`${escapeBacktick(t.noCommerceBody)}\`,\n`);
  }
  toolParts.push("};\n");

  return {
    promptsModule: promptParts.join(""),
    toolDescriptionsModule: toolParts.join(""),
  };
}

/**
 * Emit `routing-examples.generated.ts` for @leadbay/core.
 *
 * The `routing.examples` in each template are a test set, not description
 * text: realistic sentences that should call the tool, and confusable ones
 * that should call a different one. They used to ship inside the description,
 * where they cost 17,223 characters in the window hosts keep. Here they stay
 * checkable — the routing audit counts them, and the eval lane can replay
 * them — without being paid for in every session.
 */
export function emitRoutingExamples(result: AssembleResult): string {
  const parts: string[] = [HEADER];
  parts.push(
    "// Routing test set per tool: sentences that SHOULD call it (positive) and\n" +
      "// confusable ones that should NOT (negative). Not shipped in descriptions.\n",
  );
  parts.push(
    "export interface RoutingExamples {\n  positive: string[];\n  negative: string[];\n}\n\n",
  );
  parts.push("export const ROUTING_EXAMPLES: Record<string, RoutingExamples> = {\n");
  for (const t of result.toolDescriptions) {
    const ex = t.frontmatter.routing?.examples;
    if (!ex) continue;
    const pos = (ex.positive ?? []).map((s) => JSON.stringify(s.trim()));
    const neg = (ex.negative ?? []).map((s) => JSON.stringify(s.trim()));
    if (pos.length === 0 && neg.length === 0) continue;
    parts.push(`  ${t.frontmatter.name}: {\n`);
    parts.push(`    positive: [${pos.join(", ")}],\n`);
    parts.push(`    negative: [${neg.join(", ")}],\n`);
    parts.push("  },\n");
  }
  parts.push("};\n");
  return parts.join("");
}

/**
 * Emit `render-blocks.generated.ts` for @leadbay/core.
 *
 * Holds what `{{render}}` cut out of each description: the full presentation
 * algorithm, keyed by tool name, plus the one-line recipe from the template's
 * `rendering_hint`. The MCP server puts the recipe on every result of that
 * tool, and `leadbay_render_guide` returns the full block when the agent wants
 * the detail. Neither channel is truncated at 2,048 characters the way a tool
 * description is in Claude Code.
 *
 * `NO_COMMERCE_RENDER_BLOCKS` is the same text with the `{{commerce}}` parts
 * deleted, for the ChatGPT surface — the render block travels the same
 * commerce path as the description it came from.
 */
export function emitRenderBlocks(result: AssembleResult): string {
  const parts: string[] = [HEADER];
  parts.push(
    "// Presentation blocks lifted out of tool descriptions by the {{render}}\n" +
      "// marker. Keyed by tool name. Served with the RESULT, never inside the\n" +
      "// description, because hosts truncate descriptions.\n",
  );
  parts.push("export const RENDER_BLOCKS: Record<string, string> = {\n");
  for (const t of result.toolDescriptions) {
    if (!t.renderBlock) continue;
    parts.push(`  ${t.frontmatter.name}: \`${escapeBacktick(t.renderBlock)}\`,\n`);
  }
  parts.push("};\n\n");
  parts.push(
    "// The same blocks with the {{commerce}} parts deleted. Nothing is reworded.\n",
  );
  parts.push("export const NO_COMMERCE_RENDER_BLOCKS: Record<string, string> = {\n");
  for (const t of result.toolDescriptions) {
    if (!t.noCommerceRenderBlock) continue;
    parts.push(`  ${t.frontmatter.name}: \`${escapeBacktick(t.noCommerceRenderBlock)}\`,\n`);
  }
  parts.push("};\n\n");
  parts.push(
    "// One-line recipe per tool, from the template's `rendering_hint`. Rides on\n" +
      "// every result so the agent can render without fetching the full block.\n",
  );
  const recipeOf = (hint: string, mode: "with" | "without") =>
    renderCommerce(hint, mode).replace(/\s+/g, " ").trim();
  parts.push("export const RENDER_RECIPES: Record<string, string> = {\n");
  for (const t of result.toolDescriptions) {
    const hint = t.frontmatter.rendering_hint;
    if (!t.renderBlock || !hint) continue;
    parts.push(`  ${t.frontmatter.name}: \`${escapeBacktick(recipeOf(hint, "with"))}\`,\n`);
  }
  parts.push("};\n\n");
  parts.push(
    "// The same recipes with the {{commerce}} parts deleted. The recipe rides on\n" +
      "// EVERY result, so it needs the same gate the block and the description have:\n" +
      "// a rendering_hint may name a top-up (leadbay_extend_lens does today).\n",
  );
  parts.push("export const NO_COMMERCE_RENDER_RECIPES: Record<string, string> = {\n");
  for (const t of result.toolDescriptions) {
    const hint = t.frontmatter.rendering_hint;
    if (!t.renderBlock || !hint || !hasCommerceMarkers(hint)) continue;
    parts.push(`  ${t.frontmatter.name}: \`${escapeBacktick(recipeOf(hint, "without"))}\`,\n`);
  }
  parts.push("};\n");
  return parts.join("");
}

/**
 * Emit a TS module exporting one string constant per `.md` file in the given
 * directory. Used for ambient MCP server-instruction paragraphs — content
 * that the `initialize` handler concatenates into the `instructions` payload
 * the agent reads on every session. Living here in promptforge keeps the
 * paragraphs alongside the rest of the prompt content (tool descriptions,
 * slash-command prompts, snippets) and out of hand-edited `server.ts`.
 *
 * Filename convention: kebab-case `.md` → SCREAMING_SNAKE_CASE TS const.
 * `friction.md` → `FRICTION`. `quota-topup.md` → `QUOTA_TOPUP`. Plain `.md`,
 * no frontmatter — the file's full body becomes the string value, trimmed
 * of trailing newlines.
 */
export function emitServerInstructions(snippetsDir: string): string {
  if (!existsSync(snippetsDir)) {
    throw new Error(`server-instructions dir does not exist: ${snippetsDir}`);
  }
  const files = readdirSync(snippetsDir)
    .filter((f) => f.endsWith(".md"))
    .sort();
  if (files.length === 0) {
    throw new Error(`no .md files found in ${snippetsDir}`);
  }
  const parts: string[] = [HEADER];
  parts.push("// Server-instruction paragraphs, alphabetized by filename.\n");
  parts.push(
    "// Source-of-truth: packages/promptforge/snippets/server-instructions/*.md\n\n",
  );
  for (const file of files) {
    const stem = file.replace(/\.md$/, "");
    const constName = stem.replace(/-/g, "_").toUpperCase();
    if (!/^[A-Z][A-Z0-9_]*$/.test(constName)) {
      throw new Error(
        `server-instructions filename "${file}" does not produce a valid TS identifier (got "${constName}")`,
      );
    }
    const content = readFileSync(join(snippetsDir, file), "utf8").trimEnd();
    const escaped = escapeBacktick(content);
    parts.push(`// region: ${constName} (source: snippets/server-instructions/${file})\n`);
    parts.push(`export const ${constName}: string = \`${escaped}\`;\n`);
    parts.push(`// endregion: ${constName}\n\n`);
  }
  return parts.join("");
}

export function writeIfDifferent(path: string, content: string): { changed: boolean } {
  mkdirSync(dirname(path), { recursive: true });
  if (existsSync(path)) {
    const current = readFileSync(path, "utf8");
    if (current === content) return { changed: false };
  }
  writeFileSync(path, content, "utf8");
  return { changed: true };
}

export function diff(path: string, content: string): { matches: boolean; current: string | null } {
  if (!existsSync(path)) return { matches: false, current: null };
  const current = readFileSync(path, "utf8");
  return { matches: current === content, current };
}
